<?php
/**
*
* common.php fyrir útgáfu 3.0.7-PL1
* 
* Þýðingu Lokið:      Gunnar Guðvarðarson
* Yfirlestri lokið:   Nei
*
**/

/**
* DO NOT CHANGE
*/
if (!defined('IN_PHPBB'))
{
	exit;
}

if (empty($lang) || !is_array($lang))
{
	$lang = array();
}

// DEVELOPERS PLEASE NOTE
//
// All language files should use UTF-8 as their encoding and the files must not contain a BOM.
//
// Placeholders can now contain order information, e.g. instead of
// 'Page %s of %s' you can (and should) write 'Page %1$s of %2$s', this allows
// translators to re-order the output of data while ensuring it remains correct
//
// You do not need this where single placeholders are used, e.g. 'Message %d' is fine
// equally where a string contains only two placeholders which are used to wrap text
// in a url you again do not need to specify an order e.g., 'Click %sHERE%s' is fine
//
// Some characters you may want to copy&paste:
// ’ » “ ” …
//

$lang = array_merge($lang, array(
	'TRANSLATION_INFO'	=> '',
	'DIRECTION'			=> 'ltr',
	'DATE_FORMAT'		=> '|d. M Y - H:i|',	// 01. Jan 2007 - 16:35 (with Relative days enabled)
	'USER_LANG'			=> 'is',

	'1_DAY'			=> '1 dagur',
	'1_MONTH'		=> '1 mánuður',
	'1_YEAR'		=> '1 ár',
	'2_WEEKS'		=> '2 vikur',
	'3_MONTHS'		=> '3 mánuðir',
	'6_MONTHS'		=> '6 mánuðir',
	'7_DAYS'		=> '7 dagar',

	'ACCOUNT_ALREADY_ACTIVATED'		=> 'Aðgangurinn þinn er þegar virkur.',
	'ACCOUNT_DEACTIVATED'			=> 'Aðgangurinn þinn hefur verið gerður óvirkur af stjórnanda og aðeins þeir geta endurvirkjað hann.',
	'ACCOUNT_NOT_ACTIVATED'			=> 'Aðgangurinn þinn hefur ekki enn verið gerður virkur.',
	'ACP'							=> 'Kerfisstjórnborð',
	'ACTIVE'						=> 'virkur',
	'ACTIVE_ERROR'					=> 'Valinn aðgangur er óvirkur. Ef þú átt í erfiðleikum með að virkja aðganginn þinn, hafðu þá samband við stjórnanda.',
	'ADMINISTRATOR'					=> 'Stjórnandi',
	'ADMINISTRATORS'				=> 'Stjórnendur',
	'AGE'							=> 'Aldur',
	'AIM'							=> 'AIM',
	'ALLOWED'						=> 'Leyft',
	'ALL_FILES'						=> 'Allar skrár',
	'ALL_FORUMS'					=> 'Öll spjallsvæði',
	'ALL_MESSAGES'					=> 'Öll skilaboð',
	'ALL_POSTS'						=> 'Allir póstar',
	'ALL_TIMES'						=> 'Allir tímar miða við %1$s %2$s',
	'ALL_TOPICS'					=> 'Allar umræður',
	'AND'							=> 'og',
	'ARE_WATCHING_FORUM'			=> 'Þú hefur gerst áskrifandi og verður látinn vita ef það koma ný skilaboð á þessu spjallsvæði.',
	'ARE_WATCHING_TOPIC'			=> 'Þú hefur gerst áskrifandi og verður látinn vita ef það koma ný skilaboð í þessari umræðu.',
	'ASCENDING'						=> 'Stafrófsröðun',
	'ATTACHMENTS'					=> 'Viðhengi',
	'ATTACHED_IMAGE_NOT_IMAGE'		=> 'Myndin sem þú reyndir að senda inn er óleyfileg.',
	'AUTHOR'						=> 'Höfundur',
	'AUTH_NO_PROFILE_CREATED'		=> 'Ekki tókst að búa til notandastillingar.',
	'AVATAR_DISALLOWED_CONTENT'		=> 'Innsenda skráin er hugsanleg árásarskrá.',
	'AVATAR_DISALLOWED_EXTENSION'	=> 'Þessa skrá er ekki hægt að sjá því endingin <strong>%s</strong> er ekki leyfð.',
	'AVATAR_EMPTY_REMOTE_DATA'		=> 'Valin smámynd var ekki send inn því gögnin virðast vera ógild eða gölluð.',
	'AVATAR_EMPTY_FILEUPLOAD'		=> 'Innsend smámyndaskrá er tóm.',
	'AVATAR_INVALID_FILENAME'		=> '%s er ógilt skráarnafn.',
	'AVATAR_NOT_UPLOADED'			=> 'Ekki tókst að senda inn smámynd.',
	'AVATAR_NO_SIZE'				=> 'Ekki var hægt að greina breidd eða hæð smámyndarinnar. Vinsamlegast skrifaðu þær inn.',
	'AVATAR_PARTIAL_UPLOAD'			=> 'Valin skrá var aðeins send inn að hluta.',
	'AVATAR_PHP_SIZE_NA'			=> 'Smámyndin er of stór.<br /> Hámarksstærð samkvæmt php.ini er óþekkt.',
	'AVATAR_PHP_SIZE_OVERRUN'		=> 'Smámyndin er of stór.  Hámarksstærð samkvæmt php.ini er %d MB.',
	'AVATAR_URL_INVALID'			=> 'Slóðin sem þú gafst upp er röng/ógild.',
	'AVATAR_URL_NOT_FOUND'			=> 'Valin skrá fannst ekki.',
	'AVATAR_WRONG_FILESIZE'			=> 'Stærð smámyndarinnar verður að vera á milli 0 og %1d %2s.',
	'AVATAR_WRONG_SIZE'				=> 'Innsend smámynd er %5$d punkta breið og %6$d punkta há. Smámyndir verða að vera að minnsta kosti %1$d punktar á breidd og %2$d punktar á hæð, en ekki stærri en %3$d punktar á breidd og %4$d punktar á hæð.',

	'BACK_TO_TOP'			=> 'Fara efst',
	'BACK_TO_PREV'			=> 'Fara til baka',
	'BAN_TRIGGERED_BY_EMAIL'=> 'Netfangið þitt hefur verið bannað!',
	'BAN_TRIGGERED_BY_IP'	=> 'IP talan þín hefur verið bönnuð!',
	'BAN_TRIGGERED_BY_USER'	=> 'Notandanafnið þitt hefur verið bannað!',
	'BBCODE_GUIDE'			=> 'BBCode leiðbeiningar',
	'BCC'					=> 'BCC',
	'BIRTHDAYS'				=> 'Afmæli',
	'BOARD_BAN_PERM'		=> 'Þér hefur verið <strong>ENDANLEGA</strong> meinaður aðgangur að þessu spjallborði.<br /><br />Hafðu samband við %2$sKerfisstjóra%3$s fyrir frekari upplýsingar.',
	'BOARD_BAN_REASON'		=> 'Ástæða banns: <strong>%s</strong>',
	'BOARD_BAN_TIME'		=> 'Þér hefur tímabundið verið meinaður aðgangur að þessu spjallborði þar til <strong>%1$s</strong>.<br /><br />Hafðu samband við %2$sKerfisstjóra%3$s fyrir frekari upplýsingar.',
	'BOARD_DISABLE'			=> 'Því miður er spjallborðið læst í augnablikinu.',
	'BOARD_DISABLED'		=> 'Spjallborð er læst í augnablikinu!',
	'BOARD_UNAVAILABLE'		=> 'Því miður er of mikið álag á spjallborðinu sem stendur, reyndu aftur eftir nokkrar mínútur.',
	'BROWSING_FORUM'		=> 'Notendur sem eru að skoða spjallborðið: %1$s',
	'BROWSING_FORUM_GUEST'	=> 'Notandi að skoða þetta svæði: %1$s og %2$d gestur',
	'BROWSING_FORUM_GUESTS'	=> 'Notendur að skoða þetta svæði: %1$s og %2$d gestir',
	'BYTES'					=> 'Bæti',

	'CANCEL'				=> 'Hætta við',
	'CHANGE'				=> 'Breyta',
	'CHANGE_FONT_SIZE'		=> 'Breyta leturstærð',
	'CHANGING_PREFERENCES'	=> 'Breyta stillingum spjallborðsins',
	'CHANGING_PROFILE'		=> 'Breyti notandastillingum',
	'CLICK_VIEW_PRIVMSG'	=> '%sOpna innhólfið mitt%s',
	'COLLAPSE_VIEW'			=> 'Fella saman',
	'CLOSE_WINDOW'			=> 'Loka glugga',
	'COLOUR_SWATCH'			=> 'Litaval',
	'COMMA_SEPARATOR'		=> ', ',	// Used in pagination of ACP & prosilver, use localised comma if appropriate, eg: Ideographic or Arabic
	'CONFIRM'				=> 'Staðfesting',
	'CONFIRM_CODE'			=> 'Staðfestingarkóði',
	'CONFIRM_CODE_EXPLAIN'	=> 'Ritaðu kóðan nákvæmlega eins og hann kemur fram. Ekki er gerður greinarmunur á stórum og litlum stöfum og núll er ekki notað.',
	'CONFIRM_CODE_WRONG'	=> 'Staðfestingarkóðinn sem þú skrifaðir var rangur.',
	'CONFIRM_OPERATION'		=> 'Ertu viss um að þú viljir framkvæma þessa aðgerð?',
	'CONGRATULATIONS'		=> 'Til hamingju',
	'CONNECTION_FAILED'		=> 'Tenging mistókst.',
	'CONNECTION_SUCCESS'	=> 'Tenging tókst!',
	'COOKIES_DELETED'		=> 'Öllum kökum eytt.',
	'CURRENT_TIME'			=> 'Núna er %s',

	'DAY'					=> 'dagur',
	'DAYS'					=> 'dagar',
	'DELETE'				=> 'Eyða',
	'DELETE_ALL'			=> 'Eyða öllu',
	'DELETE_COOKIES'		=> 'Eyða vafrarakökum',
	'DELETE_MARKED'			=> 'Eyða merktum',
	'DELETE_POST'			=> 'Eyða pósti',
	'DELIMITER'				=> 'Afmarkari',
	'DESCENDING'			=> 'Öfug röðun',
	'DISABLED'				=> 'Óvirkt',
	'DISPLAY'				=> 'Sýna',
	'DISPLAY_GUESTS'		=> 'Sýna gesti',
	'DISPLAY_MESSAGES'		=> 'Sýna skilaboð frá fyrri',
	'DISPLAY_POSTS'			=> 'Sýna pósta frá fyrri',
	'DISPLAY_TOPICS'		=> 'Sýna umræður frá síðustu',
	'DOWNLOADED'			=> 'Sótt',
	'DOWNLOADING_FILE'		=> 'Sæki skrá',
	'DOWNLOAD_COUNT'		=> 'Sótt %d sinni',
	'DOWNLOAD_COUNTS'		=> 'Sótt %d sinnum',
	'DOWNLOAD_COUNT_NONE'	=> 'Ekki enn sótt',
	'VIEWED_COUNT'			=> 'Skoðað %d sinni',
	'VIEWED_COUNTS'			=> 'Skoðað %d sinnum',
	'VIEWED_COUNT_NONE'		=> 'Óskoðað',

	'EDIT_POST'							=> 'Breyta pósti',
	'EMAIL'								=> 'Senda',
	'EMAIL_ADDRESS'						=> 'Tölvupóstfang',
	'EMAIL_SMTP_ERROR_RESPONSE'			=> 'Upp kom villa við að senda tölvupóst á <strong>línu %1$s</strong>. Svar: %2$s.',
	'EMPTY_SUBJECT'						=> 'Þú verður að tilgreina viðfangsefni.',
	'EMPTY_MESSAGE_SUBJECT'				=> 'Þú verður að tilgreina viðfangsefni.',
	'ENABLED'							=> 'Virkt',
	'ENCLOSURE'							=> 'Fylgiskjal',
	'ERR_CHANGING_DIRECTORY'			=> 'Gat ekki skipt um möppu.',
	'ERR_CONNECTING_SERVER'				=> 'Ekki tókst að tengjast þjóni.',
	'ERR_JAB_AUTH'						=> 'Gat ekki staðfest Jabber þjón.',
	'ERR_JAB_CONNECT'					=> 'Gat ekki tengst Jabber þjón.',
	'ERR_UNABLE_TO_LOGIN'				=> 'Uppgefið notandanafn eða lykilorð er rangt!',
	'ERR_UNWATCHING'					=> 'Villa kom upp við að slökkva á áskrift.',
	'ERR_WATCHING'						=> 'Villa kom upp við að skrá áskrift.',
	'ERR_WRONG_PATH_TO_PHPBB'			=> 'Upp kom villa í spjallborðinu. (Villunúmer 0172 (common))',
	'EXPAND_VIEW'						=> 'Stækka sýn',
	'EXTENSION'							=> 'Viðbót',
	'EXTENSION_DISABLED_AFTER_POSTING'	=> 'Viðbótin <strong>%s</strong> hefur verið aftengd og er því nú ónothæf.',

	'FAQ'					=> 'SoS',
	'FAQ_EXPLAIN'			=> 'Spurt og Svarað',
	'FILENAME'				=> 'Skráarheiti',
	'FILESIZE'				=> 'Skráarstærð',
	'FILEDATE'				=> 'Skráardagsetning',
	'FILE_COMMENT'			=> 'Skráarlýsing',
	'FILE_NOT_FOUND'		=> 'Umbeðin skrá finnst ekki.',
	'FIND_USERNAME'			=> 'Finna notanda',
	'FOLDER'				=> 'Mappa',
	'FORGOT_PASS'			=> 'Ég gleymdi lykilorðinu mínu',
	'FORM_INVALID'			=> 'Innsent form var ógilt, reyndu aftur.',
	'FORUM'					=> 'Spjallborð',
	'FORUMS'				=> 'Spjallborð',
	'FORUMS_MARKED'			=> 'Öll spjallsvæði hafa verið merkt lesin.',
	'FORUM_CAT'				=> 'Spjall hluti',
	'FORUM_INDEX'			=> 'Forsíða',
	'FORUM_LINK'			=> 'Spjallborðshlekkur',
	'FORUM_LOCATION'		=> 'Staðsetning spjallborðs',
	'FORUM_LOCKED'			=> 'Spjallborð læst',
	'FORUM_RULES'			=> 'Reglur spjallborðsins',
	'FORUM_RULES_LINK'		=> 'Smelltu hér til að lesa reglur spjallborðsins',
	'FROM'					=> 'frá',
	'FSOCK_DISABLED'		=> 'Upp kom villa í spjallborðinu. (Villunúmer 0199 (common))', //  'Aðgerðina var ekki hægt að staðfesta því <var>fsockopen</var> hefur verið gerð óvirk eða þjónninn sem er verið að tala við er niðri.',

	'FTP_FSOCK_HOST'				=> 'FTP þjónn',
	'FTP_FSOCK_HOST_EXPLAIN'		=> 'FTP þjónn notaður fyrir síðuna þína.',
	'FTP_FSOCK_PASSWORD'			=> 'FTP lykilorð',
	'FTP_FSOCK_PASSWORD_EXPLAIN'	=> 'Lykilorð fyrir FTP notandanafnið þitt.',
	'FTP_FSOCK_PORT'				=> 'FTP tengi (port)',
	'FTP_FSOCK_PORT_EXPLAIN'		=> 'Tengi (port) notað á FTP þjóninum þínum.',
	'FTP_FSOCK_ROOT_PATH'			=> 'Slóð á phpBB',
	'FTP_FSOCK_ROOT_PATH_EXPLAIN'	=> 'Slóðin á rótina á phpBB spjallborðinu þínu.',
	'FTP_FSOCK_TIMEOUT'				=> 'FTP tímatakmörk',
	'FTP_FSOCK_TIMEOUT_EXPLAIN'		=> 'Tími, í sekúndum, sem kerfið bíður eftir svari frá þjóninum þínum.',
	'FTP_FSOCK_USERNAME'			=> 'FTP notandanafn',
	'FTP_FSOCK_USERNAME_EXPLAIN'	=> 'Notandanafn notað til að tengjast þjóninum þínum.',

	'FTP_HOST'					=> 'FTP hýsill',
	'FTP_HOST_EXPLAIN'			=> 'FTP þjónn notaður til að tengjast síðunni þinni.',
	'FTP_PASSWORD'				=> 'FTP lykilorð',
	'FTP_PASSWORD_EXPLAIN'		=> 'Lykilorð fyrir ftp aðganginn þinn.',
	'FTP_PORT'					=> 'FTP tengi (port)',
	'FTP_PORT_EXPLAIN'			=> 'Tengi (port) notað á FTP þjóninum þínum..',
	'FTP_ROOT_PATH'				=> 'Slóð á phpBB',
	'FTP_ROOT_PATH_EXPLAIN'		=> 'Slóðin frá rót að phpBB spjallborðinu þínu.',
	'FTP_TIMEOUT'				=> 'FTP tímatakmörk',
	'FTP_TIMEOUT_EXPLAIN'		=> 'Tími, í sekúndum, sem kerfið bíður eftir svari frá þjóninum þínum.',
	'FTP_USERNAME'				=> 'FTP notandanafn',
	'FTP_USERNAME_EXPLAIN'		=> 'Notendanafn notað til að tengjast þjóninum þínum.',

	'GENERAL_ERROR'				=> 'Almenn villa',
	'GB'						=> 'GB',
	'GIB'						=> 'GiB',
	'GO'						=> 'Áfram',
	'GOTO_PAGE'					=> 'Fara á síðu:',
	'GROUP'						=> 'Hópur',
	'GROUPS'					=> 'Hópar',
	'GROUP_ERR_TYPE'			=> 'Ógild tegund hóps valin.',
	'GROUP_ERR_USERNAME'		=> 'Ekkert nafn valið á hóp.',
	'GROUP_ERR_USER_LONG'		=> 'Nafn hóps of langt, hámarkslengd er 60 stafir.',
	'GUEST'						=> 'Gestur',
	'GUEST_USERS_ONLINE'		=> 'Það eru %d gestir tengdir',
	'GUEST_USERS_TOTAL'			=> '%d gestir',
	'GUEST_USERS_ZERO_ONLINE'	=> 'Það eru engir notendur tengdir',
	'GUEST_USERS_ZERO_TOTAL'	=> '0 gestir',
	'GUEST_USER_ONLINE'			=> 'Það er %d gestur tengdur',
	'GUEST_USER_TOTAL'			=> '%d gestur',
	'G_ADMINISTRATORS'			=> 'Stjórnendur',
	'G_BOTS'					=> 'Bottar',
	'G_GUESTS'					=> 'Gestir',
	'G_REGISTERED'				=> 'Skráðir notendur',
	'G_REGISTERED_COPPA'		=> 'Skráð börn (COPPA)',
	'G_GLOBAL_MODERATORS'		=> 'Póststjórar',
	'G_NEWLY_REGISTERED'		=> 'Nýskráðir Notendur',

	'HIDDEN_USERS_ONLINE'		=> '%d faldir notendur tengdir',
	'HIDDEN_USERS_TOTAL'		=> '%d faldir',
	'HIDDEN_USERS_TOTAL_AND'		=> '%d faldir og ',
	'HIDDEN_USERS_ZERO_ONLINE'	=> '0 faldir notendur tengdir',
	'HIDDEN_USERS_ZERO_TOTAL'	=> '0 faldir',
	'HIDDEN_USERS_ZERO_TOTAL_AND'	=> '0 faldir og ',
	'HIDDEN_USER_ONLINE'		=> '%d falinn notandi tengdur',
	'HIDDEN_USER_TOTAL'			=> '%d falinn',
	'HIDDEN_USER_TOTAL_AND'			=> '%d falinn og ',
	'HIDE_GUESTS'				=> 'Fela gesti',
	'HIDE_ME'					=> 'Fela stöðu mína í þetta skiptið.',
	'HOURS'						=> 'Klukkutímar',
	'HOME'						=> 'Heim',

	'ICQ'						=> 'ICQ',
	'ICQ_STATUS'				=> 'ICQ staða',	
	'IF'						=> 'Ef',
	'IMAGE'						=> 'Mynd',
	'IMAGE_FILETYPE_INVALID'	=> 'Skráargerðin %d fyrir mime týpu %s er ekki studd.',
	'IMAGE_FILETYPE_MISMATCH'	=> 'Röng skráargerð fannst: bjóst við endingu %1$s en endingin er %2$s.',
	'IN'						=> 'í',
	'INDEX'						=> 'Forsíða',
	'INFORMATION'				=> 'Upplýsingar',
	'INTERESTS'					=> 'Áhugamál',
	'INVALID_DIGEST_CHALLENGE'	=> 'Ógild áskorun.',
	'INVALID_EMAIL_LOG'			=> '<strong>%s</strong> mögulega ógilt tölvupóstfang?',
	'IP'						=> 'IP tala',
	'IP_BLACKLISTED'			=> 'Lokað er fyrir IP töluna %1$s vegna þess að hún hefur verið sett á svarta listann.  Kíktu á <a href="%2$s">%2$s</a> fyrir meiri upplýsingar.',

	'JABBER'				=> 'Jabber',
	'JOINED'				=> 'Skráður',
	'JUMP_PAGE'				=> 'Skrifaðu númer síðunnar sem þú vilt fara á.',
	'JUMP_TO'				=> 'Fara á',
	'JUMP_TO_PAGE'			=> 'Smelltu til að hoppa á síðu…',

	'KB'					=> 'KB',
	'KIB'					=> 'KiB',

	'LAST_POST'							=> 'Síðasti póstur',
	'LAST_UPDATED'						=> 'Síðast uppfært',
	'LAST_VISIT'						=> 'Síðasta heimsókn',
	'LDAP_NO_LDAP_EXTENSION'			=> 'LDAP viðbót ekki í boði.',
	'LDAP_NO_SERVER_CONNECTION'			=> 'Gat ekki tengst LDAP þjóni.',
	'LEGEND'							=> 'Stöðuheiti',
	'LOCATION'							=> 'Staðsetning',
	'LOCK_POST'							=> 'Læsa pósti',
	'LOCK_POST_EXPLAIN'					=> 'Koma í veg fyrir breytingar',
	'LOCK_TOPIC'						=> 'Læsa umræðu',
	'LOGIN'								=> 'Innskráning',
	'LOGIN_CHECK_PM'					=> 'Skráðu þig inn til að athuga einkaskilaboð.',
	'LOGIN_CONFIRMATION'				=> 'Staðfesting innskráningar',
	'LOGIN_CONFIRM_EXPLAIN'				=> 'Til að koma í veg fyrir að lykilorð séu brotin upp þá neyðir spjallborðið þig til að skrifa staðfestingarkóða eftir hámarks fjölda vitlausra innskráninga. Kóðinn er sýndur á myndinni hér að neðan. Ef af einhverjum ástæðum þú getur ekki lesið kóðann hafðu þá samband við stjórnanda',
	'LOGIN_ERROR_ATTEMPTS'				=> 'Þú ert kominn í hámark leyfðra innskráningartilrauna. Í viðbót við notandanafn og lykilorð þarftu að slá inn staðfestingarkóða sem sést á myndinni hér að neðan.',
	'LOGIN_ERROR_EXTERNAL_AUTH_APACHE'	=> 'Þú hefur ekki verið innskráður af Apache.',
	'LOGIN_ERROR_PASSWORD'				=> 'Þú gafst upp rangt notandanafn eða lykilorð. Athugaðu hvort þú hafir gert villu og reyndu aftur. Ef þú heldur áfram að fá villur hafðu þá samband við %sstjórnanda%s',
	'LOGIN_ERROR_PASSWORD_CONVERT'		=> 'Ekki var hægt að uppfæra lykilorð þitt með uppfærslunni á spjallborðinu. Vinsamlegast %spantaðu nýtt lykilorð%s. Ef þú heldur áfram að fá villur hafðu þá samband við %sstjórnanda%s',
	'LOGIN_ERROR_USERNAME'				=> 'Þú gafst upp rangt notandanafn eða lykilorð. Athugaðu hvort þú hafir gert villu og reyndu aftur. Ef þú heldur áfram að fá villur hafðu þá samband við %sstjórnanda%s',
	'LOGIN_FORUM'						=> 'Til að sjá pósta á þessu spjallsvæði verður þú að slá inn lykilorð þess.',
	'LOGIN_INFO'						=> 'Til að geta skrá þig inn verður þú að vera skráður notandi. Skráningin tekur aðeins fáein andartök og gefur þér frekari möguleika. Stjórnandi getur líka gefið aukin réttindi á skráða notendur. Áður en þú skráir þig inn skaltu kynna þér skilmála og reglur borðsins.',
	'LOGIN_VIEWFORUM'					=> 'Notendur verða að vera skráðir inn til að skoða þetta spjallborð.',
	'LOGIN_EXPLAIN_EDIT'				=> 'Til að breyta skilaboðum í þessu spjallborði verður þú að vera skráður inn.',
	'LOGIN_EXPLAIN_VIEWONLINE'			=> 'Til að sjá lista yfir tengda notendur þá verður þú að vera skráður inn.',
	'LOGOUT'							=> 'Aftengjast',
	'LOGOUT_USER'						=> 'Aftengjast [ %s ]',
	'LOG_ME_IN'							=> 'Skrá mig inn sjálfkrafa',

	'MARK'					=> 'Merkja',
	'MARK_ALL'				=> 'Merkja allt',
	'MARK_FORUMS_READ'		=> 'Merkja allt lesið',
	'MB'					=> 'MB',
	'MIB'					=> 'MiB',
	'MCP'					=> 'Stjórnborð póststjóra',
	'MEMBERLIST'			=> 'Notendur',
	'MEMBERLIST_EXPLAIN'	=> 'Sjá lista yfir meðlimi',
	'MERGE'					=> 'Sameina',
	'MERGE_POSTS'			=> 'Sameina pósta',
	'MERGE_TOPIC'			=> 'Sameina umræðu',
	'MESSAGE'				=> 'Skilaboð',
	'MESSAGES'				=> 'Skilaboð',
	'MESSAGE_BODY'			=> 'Meginmál skilaboða',
	'MINUTES'				=> 'Mínútur',
	'MODERATE'				=> 'Stjórna',
	'MODERATOR'				=> 'Póststjóri',
	'MODERATORS'			=> 'Póststjórar',
	'MONTH'					=> 'Mánuður',
	'MOVE'					=> 'Færa',
	'MSNM'					=> 'MSNM/WLM',	

	'NA'						=> 'Ekki til',
	'NEWEST_USER'				=> 'Nýjasti notandinn er <strong>%s</strong>',
	'NEW_MESSAGE'				=> 'Ný skilaboð',
	'NEW_MESSAGES'				=> 'Ný skilaboð',
	'NEW_PM'					=> '<strong>%d</strong> ný skilaboð',
	'NEW_PMS'					=> '<strong>%d</strong> ný skilaboð',
	'NEW_POST'					=> 'Nýr póstur',
	'NEW_POSTS'					=> 'Nýjir póstar',
	'NEXT'						=> 'Næstu',		// Used in pagination
	'NEXT_STEP'					=> 'Næst',
	'NEVER'						=> 'Aldrei',
	'NO'						=> 'Nei',
	'NOT_ALLOWED_MANAGE_GROUP'	=> 'Þú hefur ekki réttindi til að stilla þennann hóp.',
	'NOT_AUTHORISED'			=> 'Þú hefur ekki réttindi til að sjá þetta svæði.',
	'NOT_WATCHING_FORUM'		=> 'Þú ert ekki lengur áskrifandi að þessu spjallborði.',
	'NOT_WATCHING_TOPIC'		=> 'Þú ert ekki lengur áskrifandi að þessari umræðu.',
	'NOTIFY_ADMIN'				=> 'Vinsamlegast láttu stjórnanda eða vefstjóra vita.',
	'NOTIFY_ADMIN_EMAIL'		=> 'Vinsamlegast láttu stjórnanda eða vefstjóra vita: <a href="mailto:%1$s">%1$s</a>',
	'NO_ACCESS_ATTACHMENT'		=> 'Þú hefur ekki réttindi til að opna þessa skrá.',
	'NO_ACTION'					=> 'Engin aðgerð gefin upp.',
	'NO_ADMINISTRATORS'			=> 'Enginn sérstakur stjórnandi sér um þetta svæði.',
	'NO_AUTH_ADMIN'				=> 'Aðgangur að Kerfisstjórnborðinu er ekki leyfður vegna þess að þú hefur ekki stjórnenda réttindi.',
	'NO_AUTH_ADMIN_USER_DIFFER'	=> 'Þú getur ekki skráð þig aftur inn sem annar notandi.',
	'NO_AUTH_OPERATION'			=> 'Þú hefur ekki næg réttindi til að ljúka þessari aðgerð.',
	'NO_CONNECT_TO_SMTP_HOST'	=> 'Gat ekki tengst SMTP þjoni: %1$s : %2$s',
	'NO_BIRTHDAYS'				=> 'Engin afmæli i dag',
	'NO_EMAIL_MESSAGE'			=> 'Tölvupósturinn var tómur.',
	'NO_EMAIL_RESPONSE_CODE'	=> 'Gat ekki fengið svarkóða frá póstþjóni.',
	'NO_EMAIL_SUBJECT'			=> 'Enginn titill á tölvupósti gefinn upp.',
	'NO_FORUM'					=> 'Svæðið sem þú valdir er ekki til.',
	'NO_FORUMS'					=> 'Þetta svæði hefur engin spjallborð.',
	'NO_GROUP'					=> 'Umbeðinn notendahópur er ekki til.',
	'NO_GROUP_MEMBERS'			=> 'Þessi hópur hefur enga meðlimi.',
	'NO_IPS_DEFINED'			=> 'Engar IP tölur eða nöfn gefin upp',
	'NO_MEMBERS'				=> 'Engir meðlimir fundust við þessa leit.',
	'NO_MESSAGES'				=> 'Engin skilaboð',
	'NO_MODE'					=> 'Engin hamur uppgefinn.',
	'NO_MODERATORS'				=> 'Enginn sérstakur póststjóri sér um þetta svæði.',
	'NO_NEW_MESSAGES'			=> 'Engin ný skilaboð',
	'NO_NEW_PM'					=> '<strong>0</strong> ný skilaboð',
	'NO_NEW_POSTS'				=> 'Engin ný skilaboð',
	'NO_ONLINE_USERS'			=> 'Engir skráðir notendur',
	'NO_POSTS'					=> 'Engir póstar',
	'NO_POSTS_TIME_FRAME'		=> 'Engir svör í Þessari umræðu innan skilgreinds tímaramma.',
	'NO_FEED_ENABLED'			=> 'Vefstraumar eru ekki í boði fyrir þetta svæði.',
	'NO_FEED'					=> 'Umbeðinn vefstraumur er ekki í boði.',
	'NO_SUBJECT'				=> 'Enginn titill gefinn upp',								// Used for posts having no subject defined but displayed within management pages.
	'NO_SUCH_SEARCH_MODULE'		=> 'Uppgefinn leit í bakenda er ekki til.',
	'NO_SUPPORTED_AUTH_METHODS'	=> 'Engar auðkenningaraðferðir studdar.',
	'NO_TOPIC'					=> 'Þessi umræða er ekki til.',
	'NO_TOPIC_FORUM'			=> 'Þessi umræða er ekki lengur til.',
	'NO_TOPICS'					=> 'Það eru engar umræður né póstar á þessu svæði.',
	'NO_TOPICS_TIME_FRAME'		=> 'Engar umræður í þessu svæði innan skilgreinds tímaramma.',
	'NO_UNREAD_PM'				=> '<strong>0</strong> ólesin skilaboð',
	'NO_UPLOAD_FORM_FOUND'		=> 'Sending hafin en ekkert gilt sendingarform fannst.',
	'NO_USER'					=> 'Umbeðinn notandi er ekki til.',
	'NO_USERS'					=> 'Umbeðnir notendur eru ekki til.',
	'NO_USER_SPECIFIED'			=> 'Ekkert notandanafn var gefið upp.',

	// Nullar/Singular/Plural language entry. The key numbers define the number range in which a certain grammatical expression is valid.
	'NUM_POSTS_IN_QUEUE'		=> array(
		0			=> 'Engir póstur í biðröð',		// 0
		1			=> '1 póstur í biðröð',		// 1
		2			=> '%d póstar í biðröð',		// 2+
	),

	'OCCUPATION'				=> 'Starf',
	'OFFLINE'					=> 'Ótengd/ur',
	'ONLINE'					=> 'Tengd/ur',
	'ONLINE_BUDDIES'			=> 'Tengdir vinir',
	'ONLINE_USERS_TOTAL'		=> 'Samtals eru <strong>%d</strong> notendur tengdir :: ',
	'ONLINE_USERS_ZERO_TOTAL'	=> 'Samtals eru <strong>0</strong> notendur tengdir :: ',
	'ONLINE_USER_TOTAL'			=> 'Samtals er <strong>%d</strong> notandi tengdur :: ',
	'OPTIONS'					=> 'Valmöguleikar',

	'PAGE_OF'				=> 'Síða <strong>%1$d</strong> af <strong>%2$d</strong>',
	'PASSWORD'				=> 'Lykilorð',
	'PIXEL'					=> 'px',
	'PLAY_QUICKTIME_FILE'	=> 'Spila QuickTime skrá',
	'PM'					=> 'ES',
	'POSTING_MESSAGE'		=> 'Sendi skilaboð í %s',
	'POSTING_PRIVATE_MESSAGE'	=> 'Skrifa einkaskilaboð',
	'POST'					=> 'Póstur',
	'POST_ANNOUNCEMENT'		=> 'Tilkynning',
	'POST_STICKY'			=> 'Límt',
	'POSTED'				=> 'Sent inn',
	'POSTED_IN_FORUM'		=> 'í',
	'POSTED_ON_DATE'		=> 'þann',
	'POSTS'					=> 'Póstar',
	'POSTS_UNAPPROVED'		=> 'Að minnsta kosti einn póstur i þessari umræðu hefur ekki verið samþykktur.',
	'POST_BY_AUTHOR'		=> 'af',
	'POST_BY_FOE'			=> 'Þessi póstur var skrifaður af <strong>%1$s</strong> sem er á blokklistanum þínum. %2$sSýna þennan póst%3$s.',
	'POST_DAY'				=> '%.2f póstar á dag',
	'POST_DETAILS'			=> 'Upplýsingar um póst',
	'POST_NEW_TOPIC'		=> 'Setja inn nýja umræðu',
	'POST_PCT'				=> '%.2f%% af öllum póstum',
	'POST_PCT_ACTIVE'		=> '%.2f%% af póstum notanda',
	'POST_PCT_ACTIVE_OWN'	=> '%.2f%% af þínum póstum',
	'POST_REPLY'			=> 'Senda inn svar',
	'POST_REPORTED'			=> 'Smelltu til að lesa skýrslu',
	'POST_SUBJECT'			=> 'Titill',
	'POST_TIME'				=> 'Tími pósts',
	'POST_TOPIC'			=> 'Senda inn nýja umræðu',
	'POST_UNAPPROVED'		=> 'Þessi póstur bíður eftir samþykki',
	'PREVIEW'				=> 'Skoða',
	'PREVIOUS'				=> 'Fyrri',		// Used in pagination
	'PREVIOUS_STEP'			=> 'Fyrra',
	'PRIVACY'				=> 'Reglur um upplýsingagjöf',
	'PRIVATE_MESSAGE'		=> 'Einkaskilaboð',
	'PRIVATE_MESSAGES'		=> 'Einkaskilaboð',
	'PRIVATE_MESSAGING'		=> 'Einkaskilaboð',
	'PROFILE'				=> 'Stillingarnar mínar',

	'READING_FORUM'				=> 'Skoða umræður í %s',
	'READING_GLOBAL_ANNOUNCE'	=> 'Les tilkynningar',
	'READING_LINK'				=> 'Fylgi spjallborðs hlekk %s',
	'READING_TOPIC'				=> 'Les umræðu í %s',
	'READ_PROFILE'				=> 'Stillingar',
	'REASON'					=> 'Ástæða',
	'RECORD_ONLINE_USERS'		=> 'Flestir notendur tengdir í einu voru <strong>%1$s</strong> þann %2$s',
	'REDIRECT'					=> 'Áframsending',
	'REDIRECTS'					=> 'Samtals áframsendingar',
	'REGISTER'					=> 'Nýskráning',
	'REGISTERED_USERS'			=> 'Skráðir notendur:',
	'REG_USERS_ONLINE'			=> 'Það eru %d skráðir notendur og ',
	'REG_USERS_TOTAL'			=> '%d skráðir, ',
	'REG_USERS_TOTAL_AND'		=> '%d skráðir og ',
	'REG_USERS_ZERO_ONLINE'		=> 'Það eru 0 skráðir notendur og ',
	'REG_USERS_ZERO_TOTAL'		=> '0 skráðir, ',
	'REG_USERS_ZERO_TOTAL_AND'	=> '0 skráðir og ',
	'REG_USER_ONLINE'			=> 'Það er %d skráður notandi og ',
	'REG_USER_TOTAL'			=> '%d skráður, ',
	'REG_USER_TOTAL_AND'		=> '%d skráður og ',
	'REMOVE'					=> 'Fjarlægja',
	'REMOVE_INSTALL'			=> 'Vinsamlegast eyddu, færðu eða endurskýrðu install möppunni áður en þú notar borðið. Ef þessi mappa er enn til staðar þá verður aðeins Kerfisstjórnborðið virkt.',
	'REPLIES'					=> 'Svör',
	'REPLY_WITH_QUOTE'			=> 'Svara með tilvitnun',
	'REPLYING_GLOBAL_ANNOUNCE'	=> 'Svara tilkynningu',
	'REPLYING_MESSAGE'			=> 'Svara skilaboðum í %s',
	'REPORT_BY'					=> 'Tilkynnt af',
	'REPORT_POST'				=> 'Tilkynna þennann póst',
	'REPORTING_POST'			=> 'Tilkynni póst',
	'RESEND_ACTIVATION'			=> 'Endursenda staðfestingartölvupóst',
	'RESET'						=> 'Forstilla',
	'RESTORE_PERMISSIONS'		=> 'Endurheimta réttindi',
	'RETURN_INDEX'				=> '%sFara á forsíðu%s',
	'RETURN_FORUM'				=> '%sFara á spjallið sem var síðast heimsótt%s',
	'RETURN_PAGE'				=> '%sFara á fyrri síðu%s',
	'RETURN_TOPIC'				=> '%sFara á umræðuna sem ég var síðast í %s',
	'RETURN_TO'					=> 'Fara aftur á',
	'FEED'						=> 'Vefstraumur',
	'FEED_NEWS'					=> 'Fréttir',
	'FEED_TOPICS_ACTIVE'		=> 'Virkar Umræður',
	'FEED_TOPICS_NEW'			=> 'Nýar Umræður',
	'RULES_ATTACH_CAN'			=> 'Þú <strong>getur</strong> sent inn viðhengi á þessu spjallborði',
	'RULES_ATTACH_CANNOT'		=> 'Þú <strong>getur ekki</strong> sent inn viðhengi á þessu spjallborði',
	'RULES_DELETE_CAN'			=> 'Þú <strong>getur</strong> eytt þínum póstum á þessu spjallborði',
	'RULES_DELETE_CANNOT'		=> 'Þú <strong>getur ekki</strong> eytt þínum póstum á þessu spjallborði',
	'RULES_DOWNLOAD_CAN'		=> 'Þú <strong>getur</strong> sótt viðhengi á þessu spjallborði',
	'RULES_DOWNLOAD_CANNOT'		=> 'Þú <strong>getur ekki</strong> sótt viðhengi á þessu spjallborði',
	'RULES_EDIT_CAN'			=> 'Þú <strong>getur</strong> breytt þínum póstum á þessu spjallborði',
	'RULES_EDIT_CANNOT'			=> 'Þú <strong>getur ekki</strong> breytt þínum póstum á þessu spjallborði',
	'RULES_LOCK_CAN'			=> 'Þú <strong>getur</strong> læst þínum póstum á þessu spjallborði',
	'RULES_LOCK_CANNOT'			=> 'Þú <strong>getur ekki</strong> læst þínum póstum á þessu spjallborði',
	'RULES_POST_CAN'			=> 'Þú <strong>getur</strong> sent inn nýja pósta á þessu spjallborði',
	'RULES_POST_CANNOT'			=> 'Þú <strong>getur ekki</strong> sent inn nýja pósta á þessu spjallborði',
	'RULES_REPLY_CAN'			=> 'Þú <strong>getur</strong> svarað í umræðum á þessu spjallborði',
	'RULES_REPLY_CANNOT'		=> 'Þú <strong>getur ekki</strong> svarað í umræðum á þessu spjallborði',
	'RULES_VOTE_CAN'			=> 'Þú <strong>getur</strong> kosið í könnunum á þessu spjallborði',
	'RULES_VOTE_CANNOT'			=> 'Þú <strong>getur ekki</strong> kosið í könnunum á þessu spjallborði',

	'SEARCH'					=> 'Leit',
	'SEARCH_MINI'				=> 'Leit…',
	'SEARCH_ADV'				=> 'Ýtarleg leit',
	'SEARCH_ADV_EXPLAIN'		=> 'Sýna möguleika fyrir ýtarlega leit',
	'SEARCH_KEYWORDS'			=> 'Leita að lykilorðum',
	'SEARCHING_FORUMS'			=> 'Leita í spjallborðum',
	'SEARCH_ACTIVE_TOPICS'		=> 'Sýna virkar umræður',
	'SEARCH_FOR'				=> 'Leit að',
	'SEARCH_FORUM'				=> 'Leita í þessum spjallborðum…',	
	'SEARCH_NEW'				=> 'Sýna nýja pósta',
	'SEARCH_POSTS_BY'			=> 'Leita í póstum eftir',
	'SEARCH_SELF'				=> 'Sýna mína pósta',
	'SEARCH_TOPIC'				=> 'Leita í þessari umræðu…',
	'SEARCH_UNANSWERED'			=> 'Sýna pósta sem ekki hefur verið svarað',
	'SEARCH_UNREAD'				=> 'Skoða ólesna pósta',
	'SECONDS'					=> 'Sekúndur',
	'SELECT'					=> 'Velja',
	'SELECT_ALL_CODE'			=> 'Velja allt',
	'SELECT_DESTINATION_FORUM'	=> 'Veldu ákvörðunarstað',
	'SELECT_FORUM'				=> 'Veldu spjallsvæði',
	'SEND_EMAIL'				=> 'Senda',
	'SEND_EMAIL_USER'			=> 'Senda',				// Used as: {L_SEND_EMAIL_USER} {USERNAME} -> E-mail UserX
	'SEND_PRIVATE_MESSAGE'		=> 'Senda einkaskilaboð',
	'SETTINGS'					=> 'Stillingar',
	'SIGNATURE'					=> 'Undirskrift',
	'SKIP'						=> 'Hoppa í efni',
	'SMTP_NO_AUTH_SUPPORT'		=> 'SMTP þjónn styður ekki auðkenningu.',
	'SORRY_AUTH_READ'			=> 'Þú hefur ekki réttindi til að lesa þetta spjall.',
	'SORRY_AUTH_VIEW_ATTACH'	=> 'Þú hefur ekki réttindi til að sækja þetta viðhengi.',
	'SORT_BY'					=> 'Raða eftir',
	'SORT_JOINED'				=> 'Skráningardag',
	'SORT_LOCATION'				=> 'Staðsetningu',
	'SORT_RANK'					=> 'Stöðu',
	'SORT_POSTS'				=> 'Póstar',
	'SORT_TOPIC_TITLE'			=> 'Titli umræðu',
	'SORT_USERNAME'				=> 'Notandanafni',
	'SPLIT_TOPIC'				=> 'Skipta upp umræðu',
	'SQL_ERROR_OCCURRED'		=> 'Upp kom gagnagrunnsvilla við að opna síðuna. Vinsamlegast hafðu samband við %sstjórnandas ef þetta vandamál heldur áfram.',
	'STATISTICS'				=> 'Teljarar',
	'START_WATCHING_FORUM'		=> 'Gerast áskrifandi að svæði',
	'START_WATCHING_TOPIC'		=> 'Gerast áskrifandi að umræðu',
	'STOP_WATCHING_FORUM'		=> 'Segja upp áskrift að svæði',
	'STOP_WATCHING_TOPIC'		=> 'Segja upp áskrift að umræðu',
	'SUBFORUM'					=> 'Undirsvæði',
	'SUBFORUMS'					=> 'Undirsvæði',
	'SUBJECT'					=> 'Titill',
	'SUBMIT'					=> 'Senda',

	'TERMS_USE'			=> 'Reglur um notkun',
	'TEST_CONNECTION'	=> 'Prófa tengingu',
	'THE_TEAM'			=> 'Stjórnendur',
	'TIME'				=> 'Tími',

	'TOO_LONG'						=> 'Gildið sem þú slóst inn er of langt.',

	'TOO_LONG_AIM'					=> 'Skjánafnið er of langt.',
	'TOO_LONG_CONFIRM_CODE'			=> 'Staðfestingarkóðinn er of langur.',
	'TOO_LONG_DATEFORMAT'			=> 'Dagsetningarsniðið er of langt.',
	'TOO_LONG_ICQ'					=> 'ICQ númerið er of langt.',
	'TOO_LONG_INTERESTS'			=> 'Lýsing á áhugamálum er of löng.',
	'TOO_LONG_JABBER'				=> 'Jabber notandanafnið er of langt.',
	'TOO_LONG_LOCATION'				=> 'Staðsetningartextinn er of langur.',
	'TOO_LONG_MSN'					=> 'MSNM/WLM nafnið er of langt.',
	'TOO_LONG_NEW_PASSWORD'			=> 'Lykilorðið er of langt.',
	'TOO_LONG_OCCUPATION'			=> 'Starfslýsingin er of löng.',
	'TOO_LONG_PASSWORD_CONFIRM'		=> 'Staðfesting lykilorðisins er of löng.',
	'TOO_LONG_USER_PASSWORD'		=> 'Lykilorðið er of langt.',
	'TOO_LONG_USERNAME'				=> 'Notandanafnið er of langt.',
	'TOO_LONG_EMAIL'				=> 'Tölvupóstfangið er of langt.',
	'TOO_LONG_EMAIL_CONFIRM'		=> 'Staðfestingin fyrir tölvupóstfangið er of löng.',
	'TOO_LONG_WEBSITE'				=> 'Vefsíðuslóðin er of löng.',
	'TOO_LONG_YIM'					=> 'Yahoo! slóðin er of löng.',

	'TOO_MANY_VOTE_OPTIONS'			=> 'Þú hefur reynt að greiða atkvæði fyrir of marga möguleika.',

	'TOO_SHORT'						=> 'Gildið sem þú slóst inn er of stutt.',

	'TOO_SHORT_AIM'					=> 'Skjánafnið er of stutt.',
	'TOO_SHORT_CONFIRM_CODE'		=> 'Staðfestingarkóðinn er of stuttur.',
	'TOO_SHORT_DATEFORMAT'			=> 'Dagsetningarsniðið eru of stutt.',
	'TOO_SHORT_ICQ'					=> 'ICQ númerið er of stutt.',
	'TOO_SHORT_INTERESTS'			=> 'Lýsing á áhugamálum er of stutt.',
	'TOO_SHORT_JABBER'				=> 'Jabber notandanafnið er of stutt.',
	'TOO_SHORT_LOCATION'			=> 'Staðsetningartextinn er of stuttur.',
	'TOO_SHORT_MSN'					=> 'MSNM/WLM nafnið er of stutt.',
	'TOO_SHORT_NEW_PASSWORD'		=> 'Lykilorðið er of stutt.',
	'TOO_SHORT_OCCUPATION'			=> 'Starfslýsingin er of stutt.',
	'TOO_SHORT_PASSWORD_CONFIRM'	=> 'Staðfesting lykilorðsins er of stutt.',
	'TOO_SHORT_USER_PASSWORD'		=> 'Lykilorðið er of stutt.',
	'TOO_SHORT_USERNAME'			=> 'Notandanafnið er of stutt.',
	'TOO_SHORT_EMAIL'				=> 'Tölvupóstfangið er of stutt.',
	'TOO_SHORT_EMAIL_CONFIRM'		=> 'Staðfestingin fyrir tölvupóstfangið er of stutt.',
	'TOO_SHORT_WEBSITE'				=> 'Vefsíðuslóðin er of stutt.',
	'TOO_SHORT_YIM'					=> 'Yahoo! slóðin er of stutt.',

	'TOPIC'				=> 'Umræða',
	'TOPICS'			=> 'Umræður',
	'TOPICS_UNAPPROVED'	=> 'Að minnsta kosti ein umræða á þessu svæði hefur ekki verið samþykkt.',
	'TOPIC_ICON'		=> 'Umræðumerki',
	'TOPIC_LOCKED'		=> 'Þessi umræða er læst, þú getur ekki breytt póstum eða svarað.',
	'TOPIC_LOCKED_SHORT'=> 'Umræða læst',
	'TOPIC_MOVED'		=> 'Umræða flutt',
	'TOPIC_REVIEW'		=> 'Yfirlit yfir umræðu',
	'TOPIC_TITLE'		=> 'Titill umræðu',
	'TOPIC_UNAPPROVED'	=> 'Þessi umræða hefur ekki verið samþykkt',
	'TOTAL_ATTACHMENTS'	=> 'Viðhengi',
	'TOTAL_LOG'			=> '1 atburðaskrá',
	'TOTAL_LOGS'		=> '%d atburðaskrár',
	'TOTAL_NO_PM'		=> '0 einkaskilaboð samtals',
	'TOTAL_PM'			=> '1 einkaskilaboð samtals',
	'TOTAL_PMS'			=> '%d einkaskilaboð samtals',
	'TOTAL_POSTS'		=> 'Póstar samtals',
	'TOTAL_POSTS_OTHER'	=> 'Póstar samtals <strong>%d</strong>',
	'TOTAL_POSTS_ZERO'	=> 'Póstar samtals <strong>0</strong>',
	'TOPIC_REPORTED'	=> 'Þessi umræða hefur verið tilkynnt',
	'TOTAL_TOPICS_OTHER'=> 'Samtals umræður <strong>%d</strong>',
	'TOTAL_TOPICS_ZERO'	=> 'Samtals umræður <strong>0</strong>',
	'TOTAL_USERS_OTHER'	=> 'Meðlimir samtals <strong>%d</strong>',
	'TOTAL_USERS_ZERO'	=> 'Meðlimir samtals <strong>0</strong>',
	'TRACKED_PHP_ERROR'	=> 'Skráðar PHP villur: %s',

	'UNABLE_GET_IMAGE_SIZE'	=> 'Ekki var hægt að finna út stærð myndarinnar.',
	'UNABLE_TO_DELIVER_FILE'=> 'Ekki mögulegt að koma skrá til skila.',
	'UNKNOWN_BROWSER'		=> 'Óþekktur vafri',
	'UNMARK_ALL'			=> 'Afmerkja allt',
	'UNREAD_MESSAGES'		=> 'Ólesin skilaboð',
	'UNREAD_PM'				=> '<strong>%d</strong> ólesið skilaboð',
	'UNREAD_PMS'			=> '<strong>%d</strong> ólesin skilaboð',
	'UNWATCHED_FORUMS'			=> 'Þú ert ekki lengur áskrifandi að völdum svæðum.',
	'UNWATCHED_TOPICS'			=> 'Þú ert ekki lengur áskrifandi að völdum umræðum.',
	'UNWATCHED_FORUMS_TOPICS'	=> 'Þú ert ekki lengur áskrifandi að völdum póstum.',
	'UPDATE'				=> 'Uppfæra',
	'UPLOAD_IN_PROGRESS'	=> 'Sending er í gangi.',
	'URL_REDIRECT'			=> 'Ef vafrinn þinn leyfir ekki sjálfvirka áframsendingu %svinsamlegast smelltu HÉR til að vera sendur áfram%s.',
	'USERGROUPS'			=> 'Hópar',
	'USERNAME'				=> 'Notandanafn',
	'USERNAMES'				=> 'Notendanöfn',
	'USER_AVATAR'			=> 'Notandamynd',
	'USER_CANNOT_READ'		=> 'Þú getur ekki lesið pósta í þessu spjallborði.',
	'USER_POST'				=> '%d póstur',
	'USER_POSTS'			=> '%d póstar',
	'USERS'					=> 'Notendur',
	'USE_PERMISSIONS'		=> 'Prófa réttindi þessa notanda',

	'USER_NEW_PERMISSION_DISALLOWED'	=> 'Því miður hefur þú ekki réttindi til að nota þennann möguleika.',

	'VARIANT_DATE_SEPARATOR'	=> ' / ',	// Used in date format dropdown, eg: "Today, 13:37 / 01 Jan 2007, 13:37" ... to join a relative date with calendar date
	'VIEWED'					=> 'Skoðað',
	'VIEWING_FAQ'				=> 'Skoðar SoS',
	'VIEWING_MEMBERS'			=> 'Skoðar notandaupplýsingar',
	'VIEWING_ONLINE'			=> 'Skoðar hver er tengdur',
	'VIEWING_MCP'				=> 'Skoðar stjórnborð Póststjóra',
	'VIEWING_MEMBER_PROFILE'	=> 'Skoðar notandaupplýsingar',
	'VIEWING_PRIVATE_MESSAGES'	=> 'Skoðar einkaskilaboð',
	'VIEWING_REGISTER'			=> 'Skoðar nýskráningu',
	'VIEWING_UCP'				=> 'Skoðar stillingarnar mínar',
	'VIEWS'						=> 'Flettingar',
	'VIEW_BOOKMARKS'			=> 'Skoða bókamerki',
	'VIEW_FORUM_LOGS'			=> 'Skoða atburðaskrár',
	'VIEW_LATEST_POST'			=> 'Skoða nýjasta póstinn',
	'VIEW_NEWEST_POST'			=> 'Skoða fyrsta ólesna póstinn',
	'VIEW_NOTES'				=> 'Skoða minnispunkta notanda',
	'VIEW_ONLINE_TIME'			=> 'byggt á notendum sem voru virkir síðustu %d mínútu',
	'VIEW_ONLINE_TIMES'			=> 'byggt á notendum sem voru virkir síðustu %d mínútur',
	'VIEW_TOPIC'				=> 'Skoða umræðu',
	'VIEW_TOPIC_ANNOUNCEMENT'	=> 'Tilkynning: ',
	'VIEW_TOPIC_GLOBAL'			=> 'Tilkynning til allra: ',
	'VIEW_TOPIC_LOCKED'			=> 'Læst: ',
	'VIEW_TOPIC_LOGS'			=> 'Skoða atburðaskrár',
	'VIEW_TOPIC_MOVED'			=> 'Flutt: ',
	'VIEW_TOPIC_POLL'			=> 'Könnun: ',
	'VIEW_TOPIC_STICKY'			=> 'Límt: ',
	'VISIT_WEBSITE'				=> 'Heimsækja vefsiðu',

	'WARNINGS'			=> 'Aðvaranir',
	'WARN_USER'			=> 'Aðvara notanda',
	'WELCOME_SUBJECT'	=> 'Velkomin/n á %s spjallborðið',
	'WEBSITE'			=> 'Vefsíða',
	'WHOIS'				=> 'WhoIs uppfletting',
	'WHO_IS_ONLINE'		=> 'Hver er tengdur',
	'WRONG_PASSWORD'	=> 'Þú skrifaðir rangt lykilorð.',

	'WRONG_DATA_ICQ'			=> 'Númerið sem þú gafst upp er ekki gilt ICQ númer.',
	'WRONG_DATA_JABBER'			=> 'Nafnið sem þú gafst upp er ekki gilt Jabber nafn.',
	'WRONG_DATA_LANG'			=> 'Tungumálið sem þú valdir er ekki gilt.',
	'WRONG_DATA_WEBSITE'		=> 'Slóðin verður að vera gild vefslóð. Til dæmis http://www.einhvad.is/.',
	'WROTE'						=> 'skrifaði',

	'YEAR'				=> 'Ár',
	'YEAR_MONTH_DAY'	=> '(ÁÁÁÁ-MM-DD)',
	'YES'				=> 'Já',
	'YIM'				=> 'YIM',	
	'YOU_LAST_VISIT'	=> 'Síðasta heimsókn þín var á %s',
	'YOU_NEW_PM'		=> 'Nýtt einkaskilaboð bíður eftir þér í innhólfi þínu.',
	'YOU_NEW_PMS'		=> 'Ný einkaskilaboð bíða eftir þér í innhólfi þínu.',
	'YOU_NO_NEW_PM'		=> 'Engin ný skilaboð.',

	'datetime'			=> array(
		'TODAY'		=> 'Í dag',
		'TOMORROW'	=> 'Á morgun',
		'YESTERDAY'	=> 'Í gær',
		'AGO'		=> array(
			0		=> 'minna en mínúta síðan',
			1		=> '%d mínútu síðan',
			2		=> '%d mínútum síðan',
			60		=> '1 klukkutíma síðan',
		),

		'Sunday'	=> 'Sunnudagur',
		'Monday'	=> 'Mánudagur',
		'Tuesday'	=> 'Þriðjudagur',
		'Wednesday'	=> 'Miðvikudagur',
		'Thursday'	=> 'Fimmtudagur',
		'Friday'	=> 'Föstudagur',
		'Saturday'	=> 'Laugardagur',

		'Sun'		=> 'Sun',
		'Mon'		=> 'Mán',
		'Tue'		=> 'Þri',
		'Wed'		=> 'Mið',
		'Thu'		=> 'Fim',
		'Fri'		=> 'Fös',
		'Sat'		=> 'Lau',

		'January'	=> 'Janúar',
		'February'	=> 'Febrúar',
		'March'		=> 'Mars',
		'April'		=> 'Apríl',
		'May'		=> 'Maí',
		'June'		=> 'Júní',
		'July'		=> 'Júlí',
		'August'	=> 'Ágúst',
		'September' => 'September',
		'October'	=> 'Október',
		'November'	=> 'Nóvember',
		'December'	=> 'Desember',

		'Jan'		=> 'Jan',
		'Feb'		=> 'Feb',
		'Mar'		=> 'Mar',
		'Apr'		=> 'Apr',
		'May_short'	=> 'Maí',	// Short representation of "May". May_short used because in English the short and long date are the same for May.
		'Jun'		=> 'Jún',
		'Jul'		=> 'Júl',
		'Aug'		=> 'Ágú',
		'Sep'		=> 'Sep',
		'Oct'		=> 'Okt',
		'Nov'		=> 'Nóv',
		'Dec'		=> 'Des',
	),

	'tz'				=> array(
		'-12'	=> 'UTC - 12 klukkutímar',
		'-11'	=> 'UTC - 11 klukkutímar',
		'-10'	=> 'UTC - 10 klukkutímar',
		'-9.5'	=> 'UTC - 9:30 klukkutímar',
		'-9'	=> 'UTC - 9 klukkutímar',
		'-8'	=> 'UTC - 8 klukkutímar',
		'-7'	=> 'UTC - 7 klukkutímar',
		'-6'	=> 'UTC - 6 klukkutímar',
		'-5'	=> 'UTC - 5 klukkutímar',
		'-4.5'	=> 'UTC - 4:30 klukkutímar',
		'-4'	=> 'UTC - 4 klukkutímar',
		'-3.5'	=> 'UTC - 3:30 klukkutímar',
		'-3'	=> 'UTC - 3 klukkutímar',
		'-2'	=> 'UTC - 2 klukkutímar',
		'-1'	=> 'UTC - 1 klukkutími',
		'0'		=> 'UTC Ísland',
		'1'		=> 'UTC + 1 klukkutími',
		'2'		=> 'UTC + 2 klukkutímar',
		'3'		=> 'UTC + 3 klukkutímar',
		'3.5'	=> 'UTC + 3:30 klukkutímar',
		'4'		=> 'UTC + 4 klukkutímar',
		'4.5'	=> 'UTC + 4:30 klukkutímar',
		'5'		=> 'UTC + 5 klukkutímar',
		'5.5'	=> 'UTC + 5:30 klukkutímar',
		'5.75'	=> 'UTC + 5:45 klukkutímar',
		'6'		=> 'UTC + 6 klukkutímar',
		'6.5'	=> 'UTC + 6:30 klukkutímar',
		'7'		=> 'UTC + 7 klukkutímar',
		'8'		=> 'UTC + 8 klukkutímar',
		'8.75'	=> 'UTC + 8:45 klukkutímar',
		'9'		=> 'UTC + 9 klukkutímar',
		'9.5'	=> 'UTC + 9:30 klukkutímar',
		'10'	=> 'UTC + 10 klukkutímar',
		'10.5'	=> 'UTC + 10:30 klukkutímar',
		'11'	=> 'UTC + 11 klukkutímar',
		'11.5'	=> 'UTC + 11:30 klukkutímar',
		'12'	=> 'UTC + 12 klukkutímar',
		'12.75'	=> 'UTC + 12:45 klukkutímar',
		'13'	=> 'UTC + 13 klukkutímar',
		'14'	=> 'UTC + 14 klukkutímar',
		'dst'	=> '[ <abbr title="Sumartími">DBT</abbr> ]',
	),

	'tz_zones'	=> array(
		'-12'	=> '[UTC - 12]',
		'-11'	=> '[UTC - 11]',
		'-10'	=> '[UTC - 10]',
		'-9.5'	=> '[UTC - 9:30]',
		'-9'	=> '[UTC - 9]',
		'-8'	=> '[UTC - 8]',
		'-7'	=> '[UTC - 7]',
		'-6'	=> '[UTC - 6]',
		'-5'	=> '[UTC - 5]',
		'-4.5'	=> '[UTC - 4:30]',
		'-4'	=> '[UTC - 4]',
		'-3.5'	=> '[UTC - 3:30]',
		'-3'	=> '[UTC - 3]',
		'-2'	=> '[UTC - 2]',
		'-1'	=> '[UTC - 1]',
		'0'		=> '[UTC] Ísland',
		'1'		=> '[UTC + 1]',
		'2'		=> '[UTC + 2]',
		'3'		=> '[UTC + 3]',
		'3.5'	=> '[UTC + 3:30]',
		'4'		=> '[UTC + 4]',
		'4.5'	=> '[UTC + 4:30]',
		'5'		=> '[UTC + 5]',
		'5.5'	=> '[UTC + 5:30]',
		'5.75'	=> '[UTC + 5:45]',
		'6'		=> '[UTC + 6]',
		'6.5'	=> '[UTC + 6:30]',
		'7'		=> '[UTC + 7]',
		'8'		=> '[UTC + 8]',
		'8.75'	=> '[UTC + 8:45]',
		'9'		=> '[UTC + 9]',
		'9.5'	=> '[UTC + 9:30]',
		'10'	=> '[UTC + 10]',
		'10.5'	=> '[UTC + 10:30]',
		'11'	=> '[UTC + 11]',
		'11.5'	=> '[UTC + 11:30]',
		'12'	=> '[UTC + 12]',
		'12.75'	=> '[UTC + 12:45]',
		'13'	=> '[UTC + 13]',
		'14'	=> '[UTC + 14]',
	),

	// The value is only an example and will get replaced by the current time on view
	'dateformats'	=> array(
		'd M Y, H:i'			=> '01 Jan 2007, 13:37',
		'd M Y H:i'				=> '01 Jan 2008 13:37',
		'M jS, \'y, H:i'		=> 'Jan 1st, \'08, 13:37',
		'D M d, Y g:i a'		=> 'Mán Jan 01, 2008 1:37 pm',
		'F jS, Y, g:i a'		=> 'Janúar 1st, 2007, 1:37 pm',
		'|d M Y|, H:i'			=> 'Í dag, 13:37 / 01 Jan 2008, 13:37',
		'|F jS, Y|, g:i a'		=> 'Í dag, 1:37 pm / Janúar 1st, 2008, 1:37 pm'
	),

	// The default dateformat which will be used on new installs in this language
	// Translators should change this if a the usual date format is different
	'default_dateformat'	=> 'd. M Y - H:i:s', // 01. Jan 2008 - 13:37:55

));

?>
