<?php
/**
*
* ucp.php fyrir útgáfu 3.0.7-PL1
* 
* Þýðingu Lokið:      Gunnar Guðvarðarson, Gabríel A. Pétursson
* Yfirlestri lokið:   Nei
*
**/

/**
* DO NOT CHANGE
*/
if (!defined('IN_PHPBB'))
{
	exit;
}

if (empty($lang) || !is_array($lang))
{
	$lang = array();
}

// DEVELOPERS PLEASE NOTE
//
// All language files should use UTF-8 as their encoding and the files must not contain a BOM.
//
// Placeholders can now contain order information, e.g. instead of
// 'Page %s of %s' you can (and should) write 'Page %1$s of %2$s', this allows
// translators to re-order the output of data while ensuring it remains correct
//
// You do not need this where single placeholders are used, e.g. 'Message %d' is fine
// equally where a string contains only two placeholders which are used to wrap text
// in a url you again do not need to specify an order e.g., 'Click %sHERE%s' is fine

// Privacy policy and T&C
$lang = array_merge($lang, array(
	'TERMS_OF_USE_CONTENT'	=> 'Með því að nota „%1$s“ (héðan í frá „við“, „okkur“, „%1$s“, „%2$s“), þá samþykkir þú að vera lögbundin(n) eftirfarandi skilmálum. Ef þú samþykkir ekki að vera lögbundin(n) af öllum eftirfarandi skilmálum þá hefurðu ekki rétt á að skoða „%1$s“. Við höldum þeim rétt að breyta þessum skilmálum hvenær sem er án fyrirvara, svo það er á þinni ábyrgð að skoða þessa skilmála reglulega þar sem allar breytingar gilda um þig líka.<br />
	<br />
	Spjallborð okkar keyrir á hugbúnaðinum phpBB (héðan í frá „þeir“, „þeim“, „þeirra“, „phpBB hugbúnaður“, „phpbb.com“, „phpBB Hópurinn“, „phpBB liðin“) sem er spjallborðahugbúnaður gefinn út undir „<a href="http://opensource.org/licenses/gpl-license.php">General Public License</a>“ (héðan í frá „GPL“) og er hægt að sækja frá <a href="http://phpbb.com/">phpbb.com</a>. phpBB hugbúnaður býður aðeins uppá hugbúnað til að gera umræðu á netinu mögulega og ber enga ábyrgð á efni hvers og eins spjallborðs og phpBB hópurinn ber enga ábyrgð á hvað er leyft hjá okkur. Fyrir meiri upplýsingar um phpBB getur þú skoðað: <a href="http://phpbb.com/">http://phpbb.com/</a>.<br />
	<br />
	Þú samþykkir að senda aldrei inn ólöglegt efni, dónaskap, kynþáttahatur, ógeðslegt, ærumeiðandi, hótanir eða kyn-tengt efni, eða neitt álíka sem gæti brotið lög viðkomandi lands, lands þar sem spjallborðið er hýst eða æru lesenda. Með því að gera það getur leitt til þess að vera bannaður endanlega, jafnvel kæru. IP tala þín er alltaf skráð til að hjálpa til við að verja spjallborðið gegn svona „ásásum“. Þú samþykkir að „%1$s“ hafi rétt til að fjarlægja, breyta, færa eða læsa öllum umræðum hvenær sem er eins og þeim finnst best. Sem notandi þá gefur þú leyfi til að allar upplýsingar sem þú sendir hingað verði opnar, þ.e. hver sem er má taka afrit af þeim og senda hvert sem er. Þó eru ákveðnar upplýsingar sem ekki verða gefnar upp til þriðja aðila án kæru á viðkomandi. „%1$s“ eða phpBB skal EKKI vera haldið í ábyrgð ef eitthver gögn komast í hendur óprúttinna aðila gegn árás tölvurefa.
	',

	'PRIVACY_POLICY'		=> 'Þessi stefna lýsir því hvernig „%1$s“ ásamt tengdum aðilum og phpBB hugbúnaðurinn nota hverjar þær upplýsingar um þig sem safnað er á meðan á notkun þinni á vefnum stendur yfir.<br />
	<br />
	Upplýsingum um þig er safnað á tvennskonar vegu.  Í fyrsta lagi þegar þú skoðar „%1$s“ býr phpBB hugbúnaður til nokkrar vafrakökur sem eru litlar textaskrár sem vafrinn þinn geymir tímabundið á tölvunni þinni.  Fyrstu tvær vafrakökurnar geyma eingöngu notandaeinkenni og nafnlaust einkenni sem eru sjálfkrafa tengd þér af phpBB hugbúnaðinum.  Þriðja vafrakakan er búin þegar þú skoðar umræður á „%1$s“ og er notuð til að geyma upplýsingar um hvaða umræður hafa verið lesnar til að gera vefinn þægilegri í notkun.<br />
	<br />
	Mögulega verða til vafrakökur sem tengjast ekki phpBB hugbúnaðinum beint þegar vefurinn „%1$s“ er skoðaður en þær falla ekki undir þetta skjal sem aðeins á við um síður sem phpBB hugbúnaðurinn býr til.  Hin leiðin til að safna upplýsingum um þig er tengd því sem þú sendir inn.  Þetta getur til dæmis verið: innlegg sem nafnlaus notandi, nýskráning á „%1$s“ og innlegg send inn eftir skráningu og meðan þú ert tengd(ur).<br />
	<br />
	Aðgangurinn þinn geymir í það minnsta upplýsingar um notandanafn þitt, lykilorðið þitt og nothæft netfang.  Upplýsingarnar um aðganginn þinn á „%1$s“ er fellur undir lög um persónuvernd í því landi sem síðan er hýst.  „%1$s“ getur beðið um meiri upplýsingar við nýskráningu og fer það eftir uppsetningu á vef „%1$s“.  Í öllu falli ræður þú í flestum tilvikum hvaða upplýsingar um þig eru gerðar opinberar.  Að auki getur þú ráðið með stillingum hvort þú færð sjálfvirkar póstsendingar frá phpBB hugbúnaðinum.<br />
	<br />
	Lykilorðið þitt er dulritað með hakkafalli svo það sé ekki sýnilegt.  Hinsvegar er þér ráðlagt að nota ekki sama lykilorðið á ólíkum vefsíðum.  Lykilorðið þitt er til þess að þú komist inn á aðgang þinn á „%1$s“ svo þú skalt gæta þess vel og undir engum kringumstæðum mun einhver frá „%1$s“, phpBB eða öðrum þriðja aðila, biðja þig um lykilorðið þitt.  Ef þú skildir gleyma lykilorðinu þá er hægt að nota „Ég gleymdi lykilorðinu“ möguleikann í phpBB hugbúnaðinum.  Það ferli mun biðja þig um notandanafnið þitt og lykilorð og þá búa til nýtt lykilorð fyrir þig svo þú komist aftur inn.<br />
	<br />
	',
));

// Common language entries
$lang = array_merge($lang, array(
	'ACCOUNT_ACTIVE'				=> 'Aðgangur þinn er nú virkur, Takk fyrir að skrá þig.',
	'ACCOUNT_ACTIVE_ADMIN'			=> 'Aðgangurinn hefur verið virkjaður.',
	'ACCOUNT_ACTIVE_PROFILE'		=> 'Aðgangur þinn hefur nú verið endurvirkjaður.',
	'ACCOUNT_ADDED'					=> 'Takk fyrir að skrá þig, aðgangur þinn hefur verið búinn til. Þú getur nú skráð þig inn með notandanafninu og lykilorðinu sem þú valdir.',
	'ACCOUNT_COPPA'					=> 'Aðgangur þinn hefur verið búinn til en þarf að staðfesta, athugaðu tölvupóstinn þinn.',
	'ACCOUNT_EMAIL_CHANGED'			=> 'Aðgangur þinn hefur verið uppfærður. En þetta spjallborð vill að þú staðfestir nýja tölvupóstfangið, vinsamlegast athugaðu tölvupóstinn þinn.',
	'ACCOUNT_EMAIL_CHANGED_ADMIN'	=> 'Aðgangur þinn hefur verið uppfærður. En þetta spjallborð vill að stjórnendur fari yfir allar svona breytingar. Þú munt fá tölvupóst þegar því hefur verið lokið.',
	'ACCOUNT_INACTIVE'				=> 'Aðgangur þinn hefur verið uppfærður. En þetta spjallborð vill að þú staðfestir nýa tölvupóstfangið, vinsamlegast athugaðu tölvupóstinn þinn.',
	'ACCOUNT_INACTIVE_ADMIN'		=> 'Aðgangur þinn hefur verið búinn til. En þetta spjallborð vill að stjórnendur fari yfir allar svona breytingar. Þú munt fá tölvupóst þegar því hefur verið lokið.',
	'ACTIVATION_EMAIL_SENT'			=> 'Tölvupóstur til staðfestingar hefur verið sendur til þín.',
	'ACTIVATION_EMAIL_SENT_ADMIN'	=> 'Tölvupóstur til staðfestingar hefur verið sendur til stjórnenda.',
	'ADD'							=> 'Bæta við',
	'ADD_BCC'						=> 'Bæta við [BCC]',
	'ADD_FOES'						=> 'Bæta við óvinum',
	'ADD_FOES_EXPLAIN'				=> 'Þú getur sett marga í einu, hvert notandanafn í eina línu.',
	'ADD_FOLDER'					=> 'Bæta við möppu',
	'ADD_FRIENDS'					=> 'Bæta við vinum',
	'ADD_FRIENDS_EXPLAIN'			=> 'Þú getur sett marga í einu, hvert notandanafn í eina línu.',
	'ADD_NEW_RULE'					=> 'Bæta við nýrri reglu',
	'ADD_RULE'						=> 'Bæta við reglu',
	'ADD_TO'						=> 'Bæta við [Til]',
	'ADD_USERS_UCP_EXPLAIN'			=> 'Here you can add new users to the group. You may select whether this group becomes the new default for the selected users. Please enter each username on a separate line.',
	'ADMIN_EMAIL'					=> 'Stjórnendur mega hafa samband með tölvupóst',
	'AGREE'							=> 'Ég samþykki þessa skilmála',
	'ALLOW_PM'						=> 'Notendur mega senda mér einkaskilaboð',
	'ALLOW_PM_EXPLAIN'				=> 'Athugaðu að stjórnendur og póststjórar geta alltaf sent þér einkaskilaboð.',
	'ALREADY_ACTIVATED'				=> 'Þessi aðgangur er þegar virkur.',
	'ATTACHMENTS_EXPLAIN'			=> 'Þetta er listi af skrám sem þú hefur sett í pósta á þessu spjallborði.',
	'ATTACHMENTS_DELETED'			=> 'Viðhengjum eytt.',
	'ATTACHMENT_DELETED'			=> 'Viðhengi eytt.',
	'AVATAR_CATEGORY'				=> 'Flokkur',
	'AVATAR_EXPLAIN'				=> 'Hámarksstærðir; breidd: %1$d punktar, hæð: %2$d punktar, skráarstærð: %3$dkB.',
	'AVATAR_FEATURES_DISABLED'		=> 'Smámyndir eru ekki leyfðar.',
	'AVATAR_GALLERY'				=> 'Myndaalbúm',
	'AVATAR_GENERAL_UPLOAD_ERROR'	=> 'Ekki tókst að vista smámynd %s.',
	'AVATAR_NOT_ALLOWED'			=> 'Your avatar cannot be displayed because avatars have been disallowed.',
	'AVATAR_PAGE'					=> 'Síða',
	'AVATAR_TYPE_NOT_ALLOWED'		=> 'Your current avatar cannot be displayed because its type has been disallowed.',

	'BACK_TO_DRAFTS'			=> 'Til baka í drög',
	'BACK_TO_LOGIN'				=> 'Fara til baka á innskráningarsíðu',
	'BIRTHDAY'					=> 'Afmæli',
	'BIRTHDAY_EXPLAIN'			=> 'Ef þú setur ártal hér að þá verður afmæli þitt gefið upp á spjallborðinu.',
	'BOARD_DATE_FORMAT'			=> 'Tímastillingar',
	'BOARD_DATE_FORMAT_EXPLAIN'	=> 'Stillt með PHP <a href="http://www.php.net/date">date()</a> fallinu.',
	'BOARD_DST'					=> 'Sumartími <abbr title="Daylight Saving Time">DST</abbr> er virkur',
	'BOARD_LANGUAGE'			=> 'Tungumál',
	'BOARD_STYLE'				=> 'Útlit spjallborðsins',
	'BOARD_TIMEZONE'			=> 'Tímabelti mitt',
	'BOOKMARKS'					=> 'Merki',
	'BOOKMARKS_EXPLAIN'			=> 'Þú getur merkt umræður sem þú getur skoðað seinna. Hakaðu í línur sem þú vilt eyða, smelltu svo á <em>Fjarlægja merki</em> takkann.',
	'BOOKMARKS_DISABLED'		=> 'Merki eru ekki virk á þessu spjallborði.',
	'BOOKMARKS_REMOVED'			=> 'Merki fjarlægt.',

	'CANNOT_EDIT_MESSAGE_TIME'	=> 'Þú getur ekki breytt eða eytt þessum skilaboðum.',
	'CANNOT_MOVE_TO_SAME_FOLDER'=> 'Ekki hægt að færa skilaboðin í möppuna sem þú vilt fjarlægja.',
	'CANNOT_MOVE_FROM_SPECIAL'	=> 'Ekki hægt að vista skilaboðin í úthólfinu.',
	'CANNOT_RENAME_FOLDER'		=> 'Ekki er hægt að endurnefna þessa möppu.',
	'CANNOT_REMOVE_FOLDER'		=> 'Ekki er hægt að fjarlægja þessa möppu.',
	'CHANGE_DEFAULT_GROUP'		=> 'Skipta um aðalhóp',
	'CHANGE_PASSWORD'			=> 'Breyta lykilorði',
	'CLICK_RETURN_FOLDER'		=> '%1$sTil baka í „%3$s“ möppuna%2$s',
	'CONFIRMATION'				=> 'Staðfesting skráningar',
	'CONFIRM_CHANGES'			=> 'Staðfesta breytingu',	
	'CONFIRM_EMAIL'				=> 'Staðfesta tölvupóstfang',
	'CONFIRM_EMAIL_EXPLAIN'		=> 'Þú þarft aðeins að gefa þetta upp ef þú ætlar að breyta tölvupóstfangi þínu.',
	'CONFIRM_EXPLAIN'			=> 'Til að koma í veg fyrir sjálfvirkar skráningar þá verðuru að fylla út reitinn hér að neðan með stöfunum sem eru hér á myndinni.',
	'VC_REFRESH'				=> 'Endurhlaða staðfestingarkóða',
	'VC_REFRESH_EXPLAIN'		=> 'Þú getur smellt á takann til að fá nýjan kóða ef þú átt í vandræðum með þennan.',

	'CONFIRM_PASSWORD'			=> 'Staðfesta lykilorð',
	'CONFIRM_PASSWORD_EXPLAIN'	=> 'Þú þarft bara að staðfesta lykilorðið ef þú ætlar að breyta því.',
	'COPPA_BIRTHDAY'			=> 'Til að halda áfram verður þú að segja okkur hvenær þú ert fæddur.',
	'COPPA_COMPLIANCE'			=> 'COPPA samstuðningur',
	'COPPA_EXPLAIN'				=> 'Athugið að það að smella á Staðfesta býr til aðganginn þinn. Hinsvegar geturu ekki notað hann fyrr en foreldri samþykkir skráninguna. Þú færð tölvupóst með upplýsingum þegar aðgangurinn hefur verið samþykktur.',
	'CREATE_FOLDER'				=> 'Ný mappa…',
	'CURRENT_IMAGE'				=> 'Núverandi mynd',
	'CURRENT_PASSWORD'			=> 'Núverandi lykilorð',
	'CURRENT_PASSWORD_EXPLAIN'	=> 'Þú verður að skrifa núverandi tölvupóstfang ef þú vilt breyta því, tölvupóstfangi eða notandanafni.',
	'CUR_PASSWORD_ERROR'		=> 'Lykilorð rangt.',
	'CUSTOM_DATEFORMAT'			=> 'Sérsniðið…',

	'DEFAULT_ACTION'			=> 'Sjálfgefin aðgerð',
	'DEFAULT_ACTION_EXPLAIN'	=> 'Þessi aðgerð keyrir ef engin önnur keyrir.',
	'DEFAULT_ADD_SIG'			=> 'Undirskrift alltaf notuð',
	'DEFAULT_BBCODE'			=> 'BBKóði alltaf virkur',
	'DEFAULT_NOTIFY'			=> 'Láta mig vita um svör',
	'DEFAULT_SMILIES'			=> 'Broskallar alltaf virkir',
	'DEFINED_RULES'				=> 'Uppgefnar reglur',
	'DELETED_TOPIC'				=> 'Umræða hefur verið fjarlægð.',
	'DELETE_ATTACHMENT'			=> 'Eyða viðhengi',
	'DELETE_ATTACHMENTS'		=> 'Eyða viðhengjum',
	'DELETE_ATTACHMENT_CONFIRM'	=> 'Ertu viss um að þú viljir eyða þessu viðhengi?',
	'DELETE_ATTACHMENTS_CONFIRM'=> 'Ertu viss um að þú viljir eyða þessum viðhengjum?',
	'DELETE_AVATAR'				=> 'Eyða mynd',
	'DELETE_COOKIES_CONFIRM'	=> 'Ertu viss um að þú viljir fjarlægja allar vafrakökurnar?',
	'DELETE_MARKED_PM'			=> 'Eyða merktum skilaboðum',
	'DELETE_MARKED_PM_CONFIRM'	=> 'Ertu viss um að þú viljir eyða öllum merktum skilaboðum?',
	'DELETE_OLDEST_MESSAGES'	=> 'Eyða elstu skilaboðunum',
	'DELETE_MESSAGE'			=> 'Eyða skilaboðum',
	'DELETE_MESSAGE_CONFIRM'	=> 'Ertu viss um að þú viljir eyða þessum einkaskilaboðum?',
	'DELETE_MESSAGES_IN_FOLDER'	=> 'Eyða öllum skilaboðum í möppunni sem þú ert að fjarlægja',
	'DELETE_RULE'				=> 'Eyða reglu',
	'DELETE_RULE_CONFIRM'		=> 'Ertu viss um að þú viljir eyða þessari reglu?',
	'DEMOTE_SELECTED'			=> 'Lækka valinn í tign',
	'DISABLE_CENSORS'			=> 'Fela dónaorð',
	'DISPLAY_GALLERY'			=> 'Sýna gallerí',
	'DOMAIN_NO_MX_RECORD_EMAIL'	=> 'Lén tölvupóstfangsins er ekki með neina gilda MX færslu.',
	'DOWNLOADS'					=> 'Niðurhal',
	'DRAFTS_DELETED'			=> 'Öllum völdum uppköstum hefur verið eytt.',
	'DRAFTS_EXPLAIN'			=> 'Hér getur þú skoðað, breytt eða eytt uppköstum.',
	'DRAFT_UPDATED'				=> 'Uppkasti hefur verið breytt.',

	'EDIT_DRAFT_EXPLAIN'		=> 'Hér getur þú breytt uppköstunum þínum. Uppköst innihalda ekki viðhengi eða skoðanakannanir.',
	'EMAIL_BANNED_EMAIL'		=> 'Það er ekki leyfilegt að nota netfangið sem þú gast upp.',
	'EMAIL_INVALID_EMAIL'		=> 'Tölvupóstfangið sem þú notaðir er rangt skrifað.',
	'EMAIL_REMIND'				=> 'Þetta er netfangið sem er tengt aðganginum þínum.  Ef þú hefur ekki breytt því í gegnum stillingarnar þá er það netfangið sem þú notaðir þegar þú skráðir þig á spjallborðið.',
	'EMAIL_TAKEN_EMAIL'			=> 'Netfangið sem þú gafst upp er þegar í notkun.',
	'EMPTY_DRAFT'				=> 'Þú verður að skrifa eitthvað til að vista uppkastið.',
	'EMPTY_DRAFT_TITLE'			=> 'Þú verður að setja titil á uppkastið.',
	'EXPORT_AS_XML'				=> 'Vista sem XML',
	'EXPORT_AS_CSV'				=> 'Vista sem CSV',
	'EXPORT_AS_CSV_EXCEL'		=> 'Vista sem CSV (Excel)',
	'EXPORT_AS_TXT'				=> 'Vista sem TXT',
	'EXPORT_AS_MSG'				=> 'Vista sem MSG',
	'EXPORT_FOLDER'				=> 'Útflytja þessa möppu',

	'FIELD_REQUIRED'					=> 'Reitinn „%s“ verður að fylla út.',
	'FIELD_TOO_SHORT'					=> 'Reiturinn „%1$s“ er of stuttur, lámarksfjöldi stafa er %2$d.',
	'FIELD_TOO_LONG'					=> 'Reiturinn „%1$s“ er of langur, hámarksfjöldi stafa er %2$d.',
	'FIELD_TOO_SMALL'					=> 'Gildið í „%1$s“ er of lágt, lámarkið er %2$d.',
	'FIELD_TOO_LARGE'					=> 'Gildið í „%1$s“ er of hátt, hámarkið er %2$d.',
	'FIELD_INVALID_CHARS_NUMBERS_ONLY'	=> 'Reiturinn „%s“ inniheldur ógild tákn, aðeins tölur eru leyfðar.',
	'FIELD_INVALID_CHARS_ALPHA_ONLY'	=> 'Reiturinn „%s“ inniheldur ógild tákn, aðeins bókstafir eru leyfðir.',
	'FIELD_INVALID_CHARS_SPACERS_ONLY'	=> 'Reiturinn „%s“ inniheldur ógild tákn, aðeins bókstafir, tölustafir, bil eða táknin -+_[] eru leyfð.',
	'FIELD_INVALID_DATE'				=> 'Reiturinn „%s“ inniheldur ógilda dagsetningu.',

	'FOE_MESSAGE'				=> 'Skilaboð frá óvini',
	'FOES_EXPLAIN'				=> 'Óvinir eru notendur sem eru almennt hunsaðir.  Innlegg frá þessum ontendum munu ekki sjást nema að litlu leiti.  Einkaskilaboð frá óvinum eru leyfð.  Athugaðu að þú getur ekki hunsað ritstjóra eða kerfisstjóra.',
	'FOES_UPDATED'				=> 'Óvinalistinn þinn hefur verið uppfærður.',
	'FOLDER_ADDED'				=> 'Mappan hefur verið búin til.',
	'FOLDER_MESSAGE_STATUS'		=> '%1$d af %2$d skilaboðum vistuð',
	'FOLDER_NAME_EMPTY'			=> 'You must enter a name for this folder.',
	'FOLDER_NAME_EXIST'			=> 'Mappan <strong>%s</strong> er þegar til.',
	'FOLDER_OPTIONS'			=> 'Möppustillingar',
	'FOLDER_RENAMED'			=> 'Tókst að endurskíra möppuna.',
	'FOLDER_REMOVED'			=> 'Tókst að henda möppunni.',
	'FOLDER_STATUS_MSG'			=> 'Mappan er %1$d%% full (%2$d af %3$d skilaboð vistuð)',
	'FORWARD_PM'				=> 'Áframsenda ES',
	'FORCE_PASSWORD_EXPLAIN'	=> 'Þú þarft að breyta lykilorðinu þínu áður en hægt sé að halda áfram.',
	'FRIEND_MESSAGE'			=> 'Skilaboð frá vini',
	'FRIENDS'					=> 'Vinir',
	'FRIENDS_EXPLAIN'			=> 'Vinir stillingin býður þér upp á flýtileið að meðlimum sem þú hefur mikil samskipti við.  Ef útlit vefsins leyfir munu innlegg frá vinum vera meira áberandi en annara.',
	'FRIENDS_OFFLINE'			=> 'Ótengdir',
	'FRIENDS_ONLINE'			=> 'Tengdir',
	'FRIENDS_UPDATED'			=> 'Vinalistinn þinn hefur verið uppfærður.',
	'FULL_FOLDER_OPTION_CHANGED'=> 'Stillingar vistaðar.',
	'FWD_ORIGINAL_MESSAGE'		=> '-------- Upprunaleg skilaboð --------',
	'FWD_SUBJECT'				=> 'Titill: %s',
	'FWD_DATE'					=> 'Dagsetning: %s',
	'FWD_FROM'					=> 'Frá: %s',
	'FWD_TO'					=> 'Til: %s',

	'GLOBAL_ANNOUNCEMENT'		=> 'Almenn tilkynning',

	'HIDE_ONLINE'				=> 'Fela tengingu',
	'HIDE_ONLINE_EXPLAIN'		=> 'Ef þú breytir þessu, þá verður það virkt við næstu innskráningu inn á spjallborðið.',
	'HOLD_NEW_MESSAGES'			=> 'Ekki samþykkja ný skilaboð (Ný skilaboð verða ekki samþykkt fyrr en nægt pláss verður laust)',
	'HOLD_NEW_MESSAGES_SHORT'	=> 'Ný skilaboð verða stoppuð',

	'IF_FOLDER_FULL'			=> 'Ef mappa er full',
	'IMPORTANT_NEWS'			=> 'Mikilvægar tilkynningar',
	'INVALID_USER_BIRTHDAY'			=> 'Afmælisdagurinn er ekki gild dagsetning.',
	'INVALID_CHARS_USERNAME'	=> 'Notandanafnið inniheldur óleyfileg tákn.',
	'INVALID_CHARS_NEW_PASSWORD'=> 'Lykilorðið inniheldur ekki rétt tákn.',
	'ITEMS_REQUIRED'			=> 'Reitir merktir með * eru nauðsynlegir og verður að fylla út.',

	'JOIN_SELECTED'				=> 'Samtengja val',

	'LANGUAGE'					=> 'Tungumál',
	'LINK_REMOTE_AVATAR'		=> 'Hlekkur utan síðu',
	'LINK_REMOTE_AVATAR_EXPLAIN'=> 'Skláðu inn slóð smámyndarinnar sem þú villt hlekkja.',
	'LINK_REMOTE_SIZE'			=> 'Myndstærð smámyndar',
	'LINK_REMOTE_SIZE_EXPLAIN'	=> 'Skilgreinið breidd og hæð smámyndar, autt ef reynast á við sjálfvirka yfirferð.',
	'LOGIN_EXPLAIN_UCP'			=> 'Please login in order to access the User Control Panel.',
	'LOGIN_REDIRECT'			=> 'Þú hefur verið skráður inn.',
	'LOGOUT_FAILED'				=> 'Þér hefur ekki verið útskráð vegna ósamvægis gagna milli vafrann þinn og gagnagrunns. Vinsamlegast hafið samband við umsjónarmann spjallborðsins ef þetta vandamál lagast ekki.',
	'LOGOUT_REDIRECT'			=> 'Þér hefur verið skráð út.',

	'MARK_IMPORTANT'				=> 'Merkja/Afmerkja sem mikilvægt',
	'MARKED_MESSAGE'				=> 'Merkt skilaboð',
	'MAX_FOLDER_REACHED'			=> 'Hámarksfjölda notendaskilgreindra mappa náð.',
	'MESSAGE_BY_AUTHOR'				=> 'af',
	'MESSAGE_COLOURS'				=> 'Litir skilaboða',
	'MESSAGE_DELETED'				=> 'Skilaboð eytt.',
	'MESSAGE_HISTORY'				=> 'Skilaboðasaga',
	'MESSAGE_REMOVED_FROM_OUTBOX'	=> 'Þetta skilaboð var eytt af höfundi þess áður en því var sent.',
	'MESSAGE_SENT_ON'				=> 'þann',
	'MESSAGE_STORED'				=> 'Þetta skilaboð var sent með góðum árangri',
	'MESSAGE_TO'					=> 'Til',
	'MESSAGES_DELETED'				=> 'Skilaboðum eytt',
	'MOVE_DELETED_MESSAGES_TO'		=> 'Færa skilaboð úr eyddri möppu yfir í',
	'MOVE_DOWN'						=> 'Færa niður',
	'MOVE_MARKED_TO_FOLDER'			=> 'Færa merkt til %s',
	'MOVE_PM_ERROR'					=> 'Villa kom upp við færslu skilaboða yfir í nýja möppuna, eingöngu %1d af %2d skilaboðum for færð.',
	'MOVE_TO_FOLDER'				=> 'Færa í möppu',
	'MOVE_UP'						=> 'Færa upp',

	'NEW_EMAIL_ERROR'				=> 'Netföngin sem skráð voru eru ekki eins.',
	'NEW_FOLDER_NAME'				=> 'Nafn nýrrar möppu',
	'NEW_PASSWORD'					=> 'Nýtt lykilorð',
	'NEW_PASSWORD_ERROR'			=> 'Lykilorðin sem skráð voru eru ekki eins.',
	'NOTIFY_METHOD'					=> 'Aðferð við tilkynningu',
	'NOTIFY_METHOD_BOTH'			=> 'Bæði',
	'NOTIFY_METHOD_EMAIL'			=> 'Netfang eingöngu',
	'NOTIFY_METHOD_EXPLAIN'			=> 'Aðferð við sendingu skilaboða gegnum spjallborðið.',
	'NOTIFY_METHOD_IM'				=> 'Jabber eingöngu',
	'NOTIFY_ON_PM'					=> 'Láta mig vita (tölvupósti) þegar ég fæ einkaskilaboð',
	'NOT_ADDED_FRIENDS_ANONYMOUS'	=> 'Þú getur ekki bætt nafnlausa notandann á vinalistann.',
	'NOT_ADDED_FRIENDS_FOES'		=> 'Þú getur ekki bætt á vinalistann óvini á óvinalistanum.',
	'NOT_ADDED_FRIENDS_FOES'		=> 'You cannot add users to your friends list who are on your foes list.',
	'NOT_ADDED_FRIENDS_SELF'		=> 'Þú getur ekki bætt sjálfum þér á vinalistann.',
	'NOT_ADDED_FOES_MOD_ADMIN'		=> 'Þú getur ekki bætt stjórnendum né póststjórum á óvinalistann.',
	'NOT_ADDED_FOES_ANONYMOUS'		=> 'Þú getur ekki bætt nafnlausa notandann á óvinalistann.',
	'NOT_ADDED_FOES_BOTS'			=> 'You cannot add bots to your foes list.',
	'NOT_ADDED_FOES_FRIENDS'		=> 'Þú getur ekki bætt vinum á vinalistanum á óvinalistann.',
	'NOT_ADDED_FOES_SELF'			=> 'Þú getur ekki bætt sjálfum þér á óvinalistann.',
	'NOT_AGREE'						=> 'Ég samþykki EKKI þessa skilmála',
	'NOT_ENOUGH_SPACE_FOLDER'		=> 'Mappan „%s“ er full. Beðin aðgerð var ekki framkvæmd.',
	'NOT_MOVED_MESSAGE'				=> 'Þú hefur eitt einkaskilaboð í haldi vegna plássleysis.',
	'NOT_MOVED_MESSAGES'			=> 'Þú hefur %d einkaskilaboð í haldi vegna plássleysis.',
	'NO_ACTION_MODE'				=> 'Engin aðgerð skilgreind.',
	'NO_AUTHOR'						=> 'Enginn höfundur skilgreindur fyrir þetta skilaboð',
	'NO_AVATAR_CATEGORY'			=> 'Ekkert',

	'NO_AUTH_DELETE_MESSAGE'		=> 'Þú hefur ekki leyfi til þess að eyða einkaskilaboðum.',
	'NO_AUTH_EDIT_MESSAGE'			=> 'Þú hefur ekki leyfi til þess að breyta einkaskilaboðum.',
	'NO_AUTH_FORWARD_MESSAGE'		=> 'Þú hefur ekki leyfi til þess að áframsenda einkaskilaboð.',
	'NO_AUTH_GROUP_MESSAGE'			=> 'Þú hefur ekki leyfi til þess að senda einkaskilaboð til hópa.',
	'NO_AUTH_PASSWORD_REMINDER'		=> 'Þú hefyr ekki leyfi til þess að sækja um nýtt lykilorð.',
	'NO_AUTH_READ_HOLD_MESSAGE'		=> 'Þú hefur ekki leyfi til þess að lesa einkaskilaboð í haldi.',
	'NO_AUTH_READ_MESSAGE'			=> 'Þú hefur ekki leyfi til þess að lesa einkaskilaboð.',
	'NO_AUTH_READ_REMOVED_MESSAGE'	=> 'Þú getur ekki lesið þessi skilaboð vegna þess að því var eytt af höfundi þess.',
	'NO_AUTH_SEND_MESSAGE'			=> 'Þú þefur ekki leyfi til þess að senda einkaskilaboð.',
	'NO_AUTH_SIGNATURE'				=> 'Þú hefur ekki leyfi til þess að skilgreina undirskrift.',

	'NO_BCC_RECIPIENT'			=> 'Engir',
	'NO_BOOKMARKS'				=> 'Þú hefur engin bókmerki.',
	'NO_BOOKMARKS_SELECTED'		=> 'Þú hefur ekki valið nein bókmerki',
	'NO_EDIT_READ_MESSAGE'		=> 'Þetta einkaskilaboð er ekki hægt að breyta vegna þess að það hefur nú þegar verið lesið.',
	'NO_EMAIL_USER'				=> 'The e-mail/username information submitted could not be found.',
	'NO_FOES'					=> 'Engir óvinir skilgreindir',
	'NO_FRIENDS'				=> 'Engir vinir skilgreindir',
	'NO_FRIENDS_OFFLINE'		=> 'Engir vinir aftengdir',
	'NO_FRIENDS_ONLINE'			=> 'Engir vinir tengdir',
	'NO_GROUP_SELECTED'			=> 'Enginn hópur skilgreindur.',
	'NO_IMPORTANT_NEWS'			=> 'Engar mikilvægar tilkynningar til staðar.',
	'NO_MESSAGE'				=> 'Einkaskilaboð fannst ekki.',
	'NO_NEW_FOLDER_NAME'		=> 'Þú þarf að skilgreina nýtt nafn á möppu.',
	'NO_NEWER_PM'				=> 'Engin nýrri skilaboð.',
	'NO_OLDER_PM'				=> 'Engin eldri skilaboð.',
	'NO_PASSWORD_SUPPLIED'		=> 'Ekki er hægt að innskrá sig án lykilorðs.',
	'NO_RECIPIENT'				=> 'Engir viðtakendur skilgreindir',
	'NO_RULES_DEFINED'			=> 'Engar reglur uppgefnar.',
	'NO_SAVED_DRAFTS'			=> 'Engin uppköst vistuð.',
	'NO_TO_RECIPIENT'			=> 'Engir',
	'NO_WATCHED_FORUMS'			=> 'Þú ert ekki ákskrifandi á neina spjallhluta.',
	'NO_WATCHED_SELECTED'		=> 'Þú hefur ekki valið neina þræði né spjallhluta sem þú ert áskrifandi að.',
	'NO_WATCHED_TOPICS'			=> 'Þú ert ekki áskrifandi á neina þræði.',

	'PASS_TYPE_ALPHA_EXPLAIN'	=> 'Lykilorð þarf að vera á milli %1$d og %2$d bókstafi á lengd, verður að innihalda blöndu af há- og lástöfum ásamt tölustöfum.',
	'PASS_TYPE_ANY_EXPLAIN'		=> 'Verður að vera %1$d til %2$d bókstafir.',
	'PASS_TYPE_CASE_EXPLAIN'	=> 'Lykilorð þarf að vera á milli %1$d og %2$d bókstafi á lengd, verður að innihalda blöndu af há- og lástöfum.',
	'PASS_TYPE_SYMBOL_EXPLAIN'	=> 'Lykilorð þarf að vera á milli %1$d og %2$d bókstafi á lengd, verður að innihalda blöndu af há- og lástöfum ásamt tölustöfum og táknum.',
	'PASSWORD'					=> 'Lykilorð',
	'PASSWORD_ACTIVATED'		=> 'Nýja lykilorðið þitt hefur verið gert virkt.',
	'PASSWORD_UPDATED'			=> 'Nýja lykilorðið þitt hefur verið sent á upprunalega netfangið þitt.',
	'PERMISSIONS_RESTORED'		=> 'Successfully restored original permissions.',
	'PERMISSIONS_RESTORED'		=> 'Tókst að færa réttindi frá <strong>%s</strong>. Þú ert nú að skoða spjallborðið með sömu réttindi og sá notandi.<br />Vinsamlegast takið eftir að stjórnendaréttindin voru ekki afrituð. Þú getur afturkallað færsluna hvenær sem þér hentar.',
	'PM_DISABLED'				=> 'Einkaskilaboð eru óvirk á þessu spjallborði.',
	'PM_FROM'					=> 'Frá',
	'PM_FROM_REMOVED_AUTHOR'	=> 'Þessi skilaboð voru send af notanda sem ekki er lengur skráður.',
	'PM_ICON'					=> 'ES merki',
	'PM_INBOX'					=> 'Innhólf',
	'PM_NO_USERS'				=> 'Viðkomandi notendur er ekki til.',
	'PM_OUTBOX'					=> 'Úthólf',
	'PM_SENTBOX'				=> 'Sent skilaboð',
	'PM_SUBJECT'				=> 'Titill skilaboðs',
	'PM_TO'						=> 'Senda til',
	'PM_USERS_REMOVED_NO_PM'	=> 'Eitthverjir notendur var ekki hægt að bæta við vegna þess að þeir hafa gert einkaskilaboð til sín óvirkt.',
	'POPUP_ON_PM'				=> 'Poppa upp glugga þegar ég fæ einkaskilaboð',
	'POST_EDIT_PM'				=> 'Breyta skilaboð',
	'POST_FORWARD_PM'			=> 'Áframsenda skilaboð',
	'POST_NEW_PM'				=> 'Ný skilaboð',
	'POST_PM_LOCKED'			=> 'Private messaging is locked',
	'POST_PM_POST'				=> 'Vitna í póst',
	'POST_QUOTE_PM'				=> 'Vitna í skilaboð',
	'POST_REPLY_PM'				=> 'Svara skilaboð',
	'PRINT_PM'					=> 'Prentskoðun',
	'PREFERENCES_UPDATED'		=> 'Stillingar þínar hafa verið uppfærðar.',
	'PROFILE_INFO_NOTICE'		=> 'Vinsamlegast athugið að allir notendur geta séð þessar upplýsingar. Ekki láta hingað neinar persónulegar upplýsingar.',
	'PROFILE_UPDATED'			=> 'Prófíll þinn hefur verið uppfærður.',

	'RECIPIENT'							=> 'Viðtakandi',
	'RECIPIENTS'						=> 'Viðtakendur',
	'REGISTRATION'						=> 'Nýskráning Notanda',
	'RELEASE_MESSAGES'					=> '%sRelease all on-hold messages%s… they will be re-sorted into the appropriate folder if enough space is made available.',
	'REMOVE_ADDRESS'					=> 'Fjarlægja slóð',
	'REMOVE_SELECTED_BOOKMARKS'			=> 'Fjarlægja valin bókmerki',
	'REMOVE_SELECTED_BOOKMARKS_CONFIRM'	=> 'Ertu viss um að þú viljir eyða öllum merktum bókmerkjum?',
	'REMOVE_BOOKMARK_MARKED'			=> 'Fjarlægja merkt bókmerki',
	'REMOVE_FOLDER'						=> 'Fjarlægja möppu',
	'REMOVE_FOLDER_CONFIRM'				=> 'Ertu viss um að þý viljir eyða þessari möppu?',
	'RENAME'							=> 'Endurskýra',
	'RENAME_FOLDER'						=> 'Endurskýra möppu',
	'REPLIED_MESSAGE'					=> 'Búið að svara',
	'REPLY_TO_ALL'						=> 'Reply to sender and all recipients.',
	'REPORT_PM'							=> 'Report private message',
	'RESIGN_SELECTED'					=> 'Uppsögn valið',
	'RETURN_FOLDER'						=> '%1$sFara aftur í fyrri möppu%2$s',
	'RETURN_UCP'						=> '%sFara aftur í stjórnborð.%s',
	'RULE_ADDED'						=> 'Regla bætt við.',
	'RULE_ALREADY_DEFINED'				=> 'Þessi regla var skilgreind áður.',
	'RULE_DELETED'						=> 'Reglu eytt.',
	'RULE_NOT_DEFINED'					=> 'Regla ekki rétt skilgreind.',
	'RULE_REMOVED_MESSAGE'				=> 'Eitt einkaskilaboð var fjarlægt vegna póstsía.',
	'RULE_REMOVED_MESSAGES'				=> '%d einkaskilaboð voru fjarlægð vegna póstsía.',

	'SAME_PASSWORD_ERROR'		=> 'Nýja lykilorðið sem stimplað var inn er það sama og núverandi lykilorð.',
	'SEARCH_YOUR_POSTS'			=> 'Sjá mína pósta',
	'SEND_PASSWORD'				=> 'Senda lykilorð',
	'SENT_AT'					=> 'Sent',
	'SHOW_EMAIL'				=> 'Notendur mega hafa samband með tölvupósti',
	'SIGNATURE_EXPLAIN'			=> 'Þetta er texti sem bætist neðaná öll skilaboð frá þér. Hágmarks lengd eru %d bókstafir.',
	'SIGNATURE_PREVIEW'			=> 'Undirskrift þín mun líta svona út í póstum',
	'SIGNATURE_TOO_LONG'		=> 'Undirskrift þín er of löng',
	'SORT'						=> 'Sort',
	'SORT_COMMENT'				=> 'Athugasemd viðhengja',
	'SORT_DOWNLOADS'			=> 'Niðurhöl',
	'SORT_EXTENSION'			=> 'Viðbót',
	'SORT_FILENAME'				=> 'Skráarnafn',
	'SORT_POST_TIME'			=> 'Tími pósts',
	'SORT_SIZE'					=> 'Stærð skrás',

	'TIMEZONE'					=> 'Tímabelti',
	'TO'						=> 'Til',
	'TOO_MANY_RECIPIENTS'		=> 'Of margir viðtakendur.',
	'TOO_MANY_REGISTERS'		=> 'Þú hefur reynt of oft að skrá þig í bili, komdu aftur eftir smá tíma',

	'UCP'						=> 'Stillingarnar mínar',
	'UCP_ACTIVATE'				=> 'Virkja aðgang',
	'UCP_ADMIN_ACTIVATE'		=> 'Athugaðu að þú þarft að eiga gilt tölvupóstfang áður en aðgangur þinn verður virkur, þú færð sendann tölvupóstfang með sérstökum hlekk sem þú verður að smella á.',
	'UCP_AIM'					=> 'AOL',
	'UCP_ATTACHMENTS'			=> 'Viðhengi',
	'UCP_COPPA_BEFORE'			=> 'Fyrir %s',
	'UCP_COPPA_ON_AFTER'		=> 'Á eða eftir %s',
	'UCP_EMAIL_ACTIVATE'		=> 'Athugaðu að þú þarft að eiga gilt tölvupóstfang áður en aðgangur þinn verður virkur, þú færð sendan tölvupóst með sérstökum hlekk sem þú verður að smella á.',
	'UCP_ICQ'					=> 'ICQ númer',
	'UCP_JABBER'				=> 'Jabber notandi',

	'UCP_MAIN'					=> 'Yfirlit',
	'UCP_MAIN_ATTACHMENTS'		=> 'Skrár',
	'UCP_MAIN_BOOKMARKS'		=> 'Merki',
	'UCP_MAIN_DRAFTS'			=> 'Uppköst',
	'UCP_MAIN_FRONT'			=> 'Forsíða',
	'UCP_MAIN_SUBSCRIBED'		=> 'Áskriftir',

	'UCP_MSNM'					=> 'Windows Live Messenger',
	'UCP_NO_ATTACHMENTS'		=> 'Þú hefur ekki vistað neinar skrár.',

	'UCP_PREFS'					=> 'Stillingar',
	'UCP_PREFS_PERSONAL'		=> 'Breyta víðtækum stillingum',
	'UCP_PREFS_POST'			=> 'Breyta póststillingum',
	'UCP_PREFS_VIEW'			=> 'Breyta sýnstillingum',
	
	'UCP_PM'					=> 'Einkaskilaboð',
	'UCP_PM_COMPOSE'			=> 'Ný skilaboð',
	'UCP_PM_DRAFTS'				=> 'Uppköst',
	'UCP_PM_OPTIONS'			=> 'Reglur, möppur &amp; stillingar',
	'UCP_PM_POPUP'				=> 'Einkaskilaboð',
	'UCP_PM_POPUP_TITLE'		=> 'Private message popup',
	'UCP_PM_UNREAD'				=> 'Unread messages',
	'UCP_PM_VIEW'				=> 'Skoða skilaboð',

	'UCP_PROFILE'				=> 'Prófíll',
	'UCP_PROFILE_AVATAR'		=> 'Breyta smámynd',
	'UCP_PROFILE_PROFILE_INFO'	=> 'Breyta prófíl',
	'UCP_PROFILE_REG_DETAILS'	=> 'Breyta notandastillingum',
	'UCP_PROFILE_SIGNATURE'		=> 'Breyta Undirskrift',

	'UCP_USERGROUPS'			=> 'Hópar',
	'UCP_USERGROUPS_MEMBER'		=> 'Hópar',
	'UCP_USERGROUPS_MANAGE'		=> 'Stjórna hópum',

	'UCP_REGISTER_DISABLE'			=> 'Nýskráning er ekki möguleg eins og stendur.',
	'UCP_REMIND'					=> 'Senda lykilorð',
	'UCP_RESEND'					=> 'Senda virknispóst',
	'UCP_WELCOME'					=> 'Velkomin(n) í stillisvæðið þitt. Héðan getur þú fylgst með, skoðað og uppfært prófíl, stillingar, áskriftir og fleira. Þú getur líka sent skilaboð til annara notenda.',
	'UCP_YIM'						=> 'Yahoo Messenger',
	'UCP_ZEBRA'						=> 'Vinir &amp; Óvinir',
	'UCP_ZEBRA_FOES'				=> 'Stjórna óvinum',
	'UCP_ZEBRA_FRIENDS'				=> 'Stjórna vinum',
	'UNDISCLOSED_RECIPIENT'			=> 'Undisclosed Recipient',
	'UNKNOWN_FOLDER'				=> 'Óþekkt mappa',
	'UNWATCH_MARKED'				=> 'Segja upp áskrift á merktum',
	'UPLOAD_AVATAR_FILE'			=> 'Upphala frá tölvunni þinni',
	'UPLOAD_AVATAR_URL'				=> 'Tengja frá slóð',
	'UPLOAD_AVATAR_URL_EXPLAIN'		=> 'Skrifaðu slóðina þar sem myndin er. Myndin verður afrituð á þetta vefsvæði.',
	'USERNAME_ALPHA_ONLY_EXPLAIN'	=> 'Notandanafn þarf að vera á milli %1$d og %2$d stafi, eingöngu bókstafir.',
	'USERNAME_ALPHA_SPACERS_EXPLAIN'=> 'Notandanafn þarf að vera á milli %1$d og %2%d stafi, eingöngu bókstafir, stafabil og stafina „-+_[]“.',
	'USERNAME_ASCII_EXPLAIN'		=> 'Notandanafn þarf að vera á milli %1$d og %2%d stafi, eingöngu stafir í ASCII stafasettinu.',
	'USERNAME_LETTER_NUM_EXPLAIN'	=> 'Notandanafn þarf að vera á milli %1$d og %2%d stafi, eingöngu bókstafi og tölustafi.',
	'USERNAME_LETTER_NUM_SPACERS_EXPLAIN'=> 'Notandanafn þarf að vera á milli %1$d og %2%d stafi, eingöngu bókstafi, tölustafi, stafabil og stafina „-+_[]“.',
	'USERNAME_CHARS_ANY_EXPLAIN'	=> 'Lengd verður að vera frá %1$d til %2$d bókstafir.',
	'USERNAME_TAKEN_USERNAME'		=> 'Skráð notendanafn er nú þegar í notkun, vinsamlegast skráið annað notendanafn',
	'USERNAME_DISALLOWED_USERNAME'	=> 'Notandanafnið sem valið var er óleyft eða inniheldur óleyfð orð. Vinsamlegast veldu annað notandanafn.',
	'USER_NOT_FOUND_OR_INACTIVE'	=> 'The usernames you specified could either not be found or are not activated users.', 'Notandanöfnin sem gefin voru upp fundust ekki eða notendur eru óvirkir.',

	'VIEW_AVATARS'				=> 'Sýna smámyndir',
	'VIEW_EDIT'					=> 'Skoða/breyta',
	'VIEW_FLASH'				=> 'Sýna Flash hreyfimyndir',
	'VIEW_IMAGES'				=> 'Sýna myndir inní póstum',
	'VIEW_NEXT_HISTORY'			=> 'Næsta ES í sögu',
	'VIEW_NEXT_PM'				=> 'Næsta ES',
	'VIEW_PM'					=> 'Skoða skilaboð',
	'VIEW_PM_INFO'				=> 'Upplýsingar um skilaboð',
	'VIEW_PM_MESSAGE'			=> '1 skilaboð',
	'VIEW_PM_MESSAGES'			=> '%d skilaboð',
	'VIEW_PREVIOUS_HISTORY'		=> 'Fyrri ES í sögu',
	'VIEW_PREVIOUS_PM'			=> 'Fyrri ES',
	'VIEW_SIGS'					=> 'Sýna undirskriftir',
	'VIEW_SMILIES'				=> 'Sýna broskalla sem myndir',
	'VIEW_TOPICS_DAYS'			=> 'Sýna umræður frá fyrri dögum',
	'VIEW_TOPICS_DIR'			=> 'Flokka umræður átt',
	'VIEW_TOPICS_KEY'			=> 'Flokka umræður eftir',
	'VIEW_POSTS_DAYS'			=> 'Sýna umræður frá fyrri dögum',
	'VIEW_POSTS_DIR'			=> 'Flokka pósta átt',
	'VIEW_POSTS_KEY'			=> 'Flokka pósta eftir',

	'WATCHED_EXPLAIN'			=> 'Hér að neðan eru umræður sem þú ert með áskrift að. Þú færð tölvupóst þegar eitthver sendir nýtt svar. Til að segja upp áskrift, hakaðu í umræðu eða spjallsvæði til að fjarlægja áskrift.',
	'WATCHED_FORUMS'			=> 'Svæði sem fylgst er með',
	'WATCHED_TOPICS'			=> 'Umræður sem fylgst er með',
	'WRONG_ACTIVATION'			=> 'Virkjunar lykillinn passar ekki við lykla í gagnagrunni.',

	'YOUR_DETAILS'				=> 'Um þig',
	'YOUR_FOES'					=> 'Óvinur þinn',
	'YOUR_FOES_EXPLAIN'			=> 'Til að fjarlægja notendanöfn, veldu þau og staðfestu.',
	'YOUR_FRIENDS'				=> 'Vinur þinn',
	'YOUR_FRIENDS_EXPLAIN'		=> 'Til að fjarlægja notendanöfn, veldu þau og staðfestu.',
	'YOUR_WARNINGS'				=> 'Aðvörunar stig',

	'PM_ACTION' => array(
		'PLACE_INTO_FOLDER'	=> 'Setja í möppu',
		'MARK_AS_READ'		=> 'Merkja sem lesið',
		'MARK_AS_IMPORTANT'	=> 'Merkja skilaboð',
		'DELETE_MESSAGE'	=> 'Eyða skilaboðum',
	),
	'PM_CHECK' => array(
		'SUBJECT'	=> 'Titill',
		'SENDER'	=> 'Sendandi',
		'MESSAGE'	=> 'Skilaboð',
		'STATUS'	=> 'Staða skilaboðs',
		'TO'		=> 'Sent til',
	),
	'PM_RULE' => array(
		'IS_LIKE'		=> 'er líkt',
		'IS_NOT_LIKE'	=> 'er ekki líkt',
		'IS'			=> 'er',
		'IS_NOT'		=> 'er ekki',
		'BEGINS_WITH'	=> 'byrjar á',
		'ENDS_WITH'		=> 'endar á',
		'IS_FRIEND'		=> 'er vinur',
		'IS_FOE'		=> 'er óvinur',
		'IS_USER'		=> 'er notandi',
		'IS_GROUP'		=> 'er í hóp',
		'ANSWERED'		=> 'svarað',
		'FORWARDED'		=> 'áframsent',
		'TO_GROUP'		=> 'í aðalhóp mínum',
		'TO_ME'			=> 'til mín',
	),


	'GROUPS_EXPLAIN'	=> 'Hópar leyfa stórnendum að ráða betur hver getur hvað. Venjulega ert þú í aðalhópnum, þetta er hann. Hópar stjórna t.d. lit notandanafnsins, smámynd, stöðu og hvort þú hafir eitthver aukaleg réttindi.',
	'GROUP_LEADER'		=> 'Leiðtogar',
	'GROUP_MEMBER'		=> 'Meðlimir',
	'GROUP_PENDING'		=> 'Ósamþykktir meðlimir',
	'GROUP_NONMEMBER'	=> 'Ekki meðlimir',
	'GROUP_DETAILS'		=> 'Upplýsingar um hóp',

	'NO_LEADER'		=> 'Enginn hópstjóri',
	'NO_MEMBER'		=> 'Enginn meðlimir hóps',
	'NO_PENDING'	=> 'Enginn ósamþykktur',
	'NO_NONMEMBER'	=> 'Enginn ósamþykktur meðlimur',
));

?>
